### ISSUE TITLE
初始化FaceLandmarker.createFromOptions，加载assets文件失败

### ISSUE THREAD

**Issue by lixiaofei41322** [google-ai-edge/mediapipe#5039]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

Android

### Mobile device if the issue happens on mobile device

小米

### Programming Language and version

Android

### MediaPipe version

0.10.0

### Solution

初始化失败

### Describe the actual behavior

加载assets文件失败

### Describe the expected behaviour

加载assets文件失败

### Standalone code/steps you may have used to try to get what you need

```shell
var cameraExecutor: ExecutorService = Executors.newSingleThreadExecutor()
        cameraExecutor.execute {
            val baseOptionBuilder = BaseOptions.builder()
            baseOptionBuilder.setDelegate(Delegate.CPU)
            baseOptionBuilder.setModelAssetPath("face.task")
            val baseOptions = baseOptionBuilder.build()
            val optionsBuilder = FaceLandmarker.FaceLandmarkerOptions.builder()
                .setBaseOptions(baseOptions)
                .setMinFaceDetectionConfidence(0.5f)
                .setMinTrackingConfidence(0.5f)
                .setMinFacePresenceConfidence(0.5f)
                .setNumFaces(1)
                .setOutputFaceBlendshapes(true)
                .setRunningMode(RunningMode.LIVE_STREAM)
                .setResultListener(this::returnLivestreamResult)
                .setErrorListener(this::returnLivestreamError)

            val options = optionsBuilder.build()
            var faceLandmarker = FaceLandmarker.createFromOptions(this@TongueCameraActivity, options)
        }
```

### Other info / Complete Logs

```shell
E  # CRASH DEVICE: fail UNROOT
2023-12-27 17:00:48.285 15801-15998 CrashReport             com.king.medical.tcm                 E  # RUNTIME AVAIL RAM:4379078656 ROM:188961550336 SD:188961550336
2023-12-27 17:00:48.285 15801-15998 CrashReport             com.king.medical.tcm                 E  # RUNTIME TOTAL RAM:7909367808 ROM:243192004608 SD:243192004608
2023-12-27 17:00:48.285 15801-15998 CrashReport             com.king.medical.tcm                 E  # CRASH STACK: 
2023-12-27 17:00:48.285 15801-15998 CrashReport             com.king.medical.tcm                 E  java.lang.RuntimeException: Field filePointerMeta_ for com.google.mediapipe.tasks.core.proto.ExternalFileProto$ExternalFile not found. Known fields are [public int com.google.mediapipe.tasks.core.proto.ExternalFileProto$ExternalFile.bitField0_, public com.google.protobuf.ByteString com.google.mediapipe.tasks.core.proto.ExternalFileProto$ExternalFile.fileContent_, public com.google.mediapipe.tasks.core.proto.ExternalFileProto$FileDescriptorMeta com.google.mediapipe.tasks.core.proto.ExternalFileProto$ExternalFile.fileDescriptorMeta_, public java.lang.String com.google.mediapipe.tasks.core.proto.ExternalFileProto$ExternalFile.fileName_, public static final com.google.mediapipe.tasks.core.proto.ExternalFileProto$ExternalFile com.google.mediapipe.tasks.core.proto.ExternalFileProto$ExternalFile.DEFAULT_INSTANCE, public static volatile com.google.protobuf.Parser com.google.mediapipe.tasks.core.proto.ExternalFileProto$ExternalFile.PARSER]
                                                                                                    	at com.google.protobuf.MessageSchema.reflectField(MessageSchema.java:614)
                                                                                                    	at com.google.protobuf.MessageSchema.newSchemaForRawMessageInfo(MessageSchema.java:507)
                                                                                                    	at com.google.protobuf.MessageSchema.newSchema(MessageSchema.java:227)
                                                                                                    	at com.google.protobuf.ManifestSchemaFactory.newSchema(ManifestSchemaFactory.java:77)
                                                                                                    	at com.google.protobuf.ManifestSchemaFactory.createSchema(ManifestSchemaFactory.java:71)
                                                                                                    	at com.google.protobuf.Protobuf.schemaFor(Protobuf.java:90)
                                                                                                    	at com.google.protobuf.Protobuf.schemaFor(Protobuf.java:104)
                                                                                                    	at com.google.protobuf.GeneratedMessageLite.makeImmutable(GeneratedMessageLite.java:175)
                                                                                                    	at com.google.protobuf.GeneratedMessageLite$Builder.buildPartial(GeneratedMessageLite.java:397)
                                                                                                    	at com.google.protobuf.GeneratedMessageLite$Builder.build(GeneratedMessageLite.java:405)
                                                                                                    	at com.google.mediapipe.tasks.core.TaskOptions.convertBaseOptionsToProto(TaskOptions.java:73)
                                                                                                    	at com.google.mediapipe.tasks.vision.facelandmarker.FaceLandmarker$FaceLandmarkerOptions.convertToCalculatorOptionsProto(FaceLandmarker.java:551)
                                                                                                    	at com.google.mediapipe.tasks.core.TaskInfo.generateGraphConfig(TaskInfo.java:116)
                                                                                                    	at com.google.mediapipe.tasks.core.TaskRunner.create(TaskRunner.java:62)
                                                                                                    	at com.google.mediapipe.tasks.vision.facelandmarker.FaceLandmarker.createFromOptions(FaceLandmarker.java:213)
                                                                                                    	at com.king.medical.tcm.pulse.ui.activity.tongue.TongueCameraActivity.openCamera$lambda-5(TongueCameraActivity.kt:245)
                                                                                                    	at com.king.medical.tcm.pulse.ui.activity.tongue.TongueCameraActivity.$r8$lambda$7hboEBRVTq4ADnwdngOUCw7c0FU(Unknown Source:0)
                                                                                                    	at com.king.medical.tcm.pulse.ui.activity.tongue.TongueCameraActivity$$ExternalSyntheticLambda4.run(Unknown Source:2)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                    	at java.lang.Thread.run(Thread.java:923)
2023-12-27 17:00:48.285 15801-15998 CrashReport             com.king.medical.tcm                 E  #++++++++++++++++++++++++++++++++++++++++++#
2023-12-27 17:00:48.287 15801-15998 CrashReport             com.king.medical.tcm                 D  [Database] insert t_cr success.
```

**Comment by schmidt-sebastian** [comment]
What version of MP Tasks Vision (`com.google.mediapipe:tasks-vision`) and MP Tasks Core (`com.google.mediapipe:tasks-core`) are you using? The field that is referenced in the error message is new, and hence you need to update Tasks Core as well.

**Comment by lixiaofei41322** [comment]
我用的com.google.mediapipe:tasks-vision:0.10.9，发现问题了是混淆代码导致的，你们混淆代码是什么啊？

**Comment by kuaashish** [comment]
Hi @lixiaofei41322,

Could you please confirm whether the issue has been resolved on your end, or if you still require assistance from our end?

Thank you!!

**Comment by AnyLifeZLB** [comment]
> 我用的com.google.mediapipe:tasks-vision:0.10.9，发现问题了是混淆代码导致的，你们混淆代码是什么啊？

@lixiaofei41322 你好，混淆代码配置有吗？官方找了一下没找到..... 谢谢
