### ISSUE TITLE
Executing ImageGenerator.createFromOptions crashes the program

### ISSUE THREAD

**Issue by ZTMIDGO** [google-ai-edge/mediapipe#5222]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

Android 14

### Mobile device if the issue happens on mobile device

Xiaomi Redmi Note 12 Turbo

### Programming Language and version

Java

### MediaPipe version

com.google.mediapipe:tasks-vision-image-generator:latest.release

### Solution

ImageGenerator

### Describe the actual behavior

An exception occurs when createFromOptions is executed

### Describe the expected behaviour

An instance of the ImageGenerator should be obtained

### Standalone code/steps you may have used to try to get what you need

```shell
new Thread(new Runnable() {
                    @Override
                    public void run() {
                        String path = getFilesDir().getAbsolutePath()+"/bins";
                        ImageGenerator.ImageGeneratorOptions options = ImageGenerator.ImageGeneratorOptions.builder().setImageGeneratorModelDirectory(path).build();
                        ImageGenerator helper = ImageGenerator.createFromOptions(MainActivity.this.getApplicationContext(), options);
                    }
                }).start();
```

### Other info / Complete Logs

```shell
11:45:19.622  E  E0000 00:00:1710301519.622072    6442 diffuser_gpu.cc:88] UNKNOWN: Failed to create 2D texture (clCreateImage): Invalid image size
11:45:19.622  E  E0000 00:00:1710301519.622527    6439 calculator_graph.cc:887] INTERNAL: CalculatorGraph::Run() failed: 
                 Calculator::Open() for node "mediapipe_tasks_vision_image_generator_imagegeneratorgraph__StableDiffusionIterateCalculator" failed: ; RET_CHECK failure (mediapipe/tasks/cc/vision/image_generator/diffuser/stable_diffusion_iterate_calculator.cc:248) context_
11:45:19.624  E  FATAL EXCEPTION: Thread-6
                 Process: com.soya.demosd, PID: 5328
                 com.google.mediapipe.framework.MediaPipeException: internal: CalculatorGraph::Run() failed: 
                 Calculator::Open() for node "mediapipe_tasks_vision_image_generator_imagegeneratorgraph__StableDiffusionIterateCalculator" failed: ; RET_CHECK failure (mediapipe/tasks/cc/vision/image_generator/diffuser/stable_diffusion_iterate_calculator.cc:248) context_
                 	at com.google.mediapipe.framework.Graph.nativeWaitUntilGraphIdle(Native Method)
                 	at com.google.mediapipe.framework.Graph.waitUntilGraphIdle(Graph.java:464)
                 	at com.google.mediapipe.tasks.core.TaskRunner.create(TaskRunner.java:74)
                 	at com.google.mediapipe.tasks.vision.imagegenerator.ImageGenerator.createFromOptions(ImageGenerator.java:167)
                 	at com.google.mediapipe.tasks.vision.imagegenerator.ImageGenerator.createFromOptions(ImageGenerator.java:96)
                 	at com.soya.demosd.MainActivity$1$1.run(MainActivity.java:34)
                 	at java.lang.Thread.run(Thread.java:1012)
```

**Comment by schmidt-sebastian** [comment]
You are getting an error from OpenCL here. I will route this issue to our GPU team.

**Comment by akashvverma1995** [comment]
Hi @ZTMIDGO 

please try upgrading to a later version of MediaPipe. However, please note that the Image Generation task has been [deprecated](https://developers.google.com/edge/mediapipe/solutions/vision/image_generator) and is no longer actively maintained.
