### ISSUE TITLE
Upgraded to mediapipe latest 0.10.12 task version , Facing RET_CHECK failure

### ISSUE THREAD

**Issue by janaki112** [google-ai-edge/mediapipe#5438]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

windows 11

### Programming Language and version

Javascript

### MediaPipe version

0.10.12

### Solution

Pose

### Describe the actual behavior

I'm trying to run mediapipe pose detection on a video  passing video stream as input to detectForVideo method, instead of landmarks i'm getting this error - polyfills.js:8451 Uncaught Error: Uncaught (in promise): Error: WaitUntilIdle failed: $CalculatorGraph::Run() failed in Run: Calculator::Process() for node "mediapipe_tasks_vision_pose_landmarker_poselandmarkergraph__mediapipe_tasks_vision_pose_detector_posedetectorgraph__mediapipe_tasks_components_processors_imagepreprocessinggraph__ImageToTensorCalculator" failed: RET_CHECK failure (third_party/mediapipe/calculators/tensor/image_to_tensor_utils.cc:56) roi->width > 0 && roi->height > 0 ROI width and height must be > 0.; WaitUntilIdle failed Error: WaitUntilIdle failed: $CalculatorGraph::Run() failed in Run: Calculator::Process() for node "mediapipe_tasks_vision_pose_landmarker_poselandmarkergraph__mediapipe_tasks_vision_pose_detector_posedetectorgraph__mediapipe_tasks_components_processors_imagepreprocessinggraph__ImageToTensorCalculator" failed: RET_CHECK failure (third_party/mediapipe/calculators/tensor/image_to_tensor_utils.cc:56) roi->width > 0 && roi->height > 0 ROI width and height must be > 0.; WaitUntilIdle failed

### Describe the expected behaviour

I need to get landmarks for the landmarks for the video 

### Standalone code/steps you may have used to try to get what you need

```shell
public motionLoadWeights({url,taskVisionUrl,clientPrompt,componentName}:{url?:string,taskVisionUrl?:string,clientPrompt?:ClientPrompts,componentName:ComponentNames}={componentName:ComponentNames.UNKNOWN}): Observable<{ motionPoseLandmarker: PoseLandmarker }> {
    let detector: PoseLandmarker;
    return from(tensorFlow.setBackend("webgl")).pipe(
      switchMap(() => (from(FilesetResolver.forVisionTasks(
        taskVisionUrl?taskVisionUrl:ModelWeightsUrls.TASK_VISION
      )))),
      switchMap((vision) => (from(PoseLandmarker.createFromOptions(vision, {
        baseOptions: {
          modelAssetPath: url?url:ModelWeightsUrls.POSE
        },
        runningMode: 'VIDEO',
        numPoses: 2
      })))),
      switchMap((config) => {
        detector = config
        return (from(detector.setOptions({ runningMode: 'VIDEO' })))
      }),
      map(() => ({ motionPoseLandmarker: detector })),
      catchError((error) => {
        try{
          this.handleErrorService.handleErrors(EventNames.MEDIAPIPE,componentName,EventsInstants.BEFORE_LOADING,error,clientPrompt?clientPrompt:ClientPrompts.GAME_DELAY,"POSE");
              }
        catch(error){
    
         if(error instanceof CdnError){
          if(error.repeatCount){
            switch(error.name){
              case ErrorNames.TASK_VISION:
                return this.motionLoadWeights({taskVisionUrl:error.altUrl,componentName:componentName,clientPrompt:clientPrompt})
              case ErrorNames.WEIGHTS:
                return this.motionLoadWeights({url:error.altUrl,componentName:componentName,clientPrompt:clientPrompt});
            }            
          }else{
            this.handleErrorService.handleErrors(EventNames.MEDIAPIPE,componentName,EventsInstants.BEFORE_LOADING,new EndOfRepeatCount(ErrorNames.END_OF_REPEAT_COUNT,ErrorMessages.END_OF_REPEAT_COUNT,ClientPrompts.END_OF_REPEAT_COUNT),ClientPrompts.END_OF_REPEAT_COUNT,"POSE");
          }
           
        }
        }
        return of(error);
      })

    )
  }
After getting model instance 
  @ViewChild('video')
  videoRef : ElementRef; this is the video reference 
  const video = this.videoRef?.nativeElement;
  let landmarks = this.poseDetector?.detectForVideo(video,performance.now()); 
while getting landmarks i'm getting the issue
```

### Other info / Complete Logs

```shell
vendor.js:31049 E0527 11:29:07.735000 1880752 image_to_tensor_utils.cc:56] INTERNAL: RET_CHECK failure (third_party/mediapipe/calculators/tensor/image_to_tensor_utils.cc:56) roi->width > 0 && roi->height > 0 ROI width and height must be > 0.
Stack trace:
polyfills.js:8451 Uncaught
Error: Uncaught (in promise): Error: Encountered multiple errors: Adding proto packet of type mediapipe.NormalizedRect to stream norm_rect was not ok: $Graph has errors: Calculator::Process() for node "mediapipe_tasks_vision_pose_landmarker_poselandmarkergraph__mediapipe_tasks_vision_pose_detector_posedetectorgraph__mediapipe_tasks_components_processors_imagepreprocessinggraph__ImageToTensorCalculator" failed: RET_CHECK failure (third_party/mediapipe/calculators/tensor/image_to_tensor_utils.cc:56) roi->width > 0 && roi->height > 0 ROI width and height must be > 0., WaitUntilIdle failed: $CalculatorGraph::Run() failed in Run: Calculator::Process() for node "mediapipe_tasks_vision_pose_landmarker_poselandmarkergraph__mediapipe_tasks_vision_pose_detector_posedetectorgraph__mediapipe_tasks_components_processors_imagepreprocessinggraph__ImageToTensorCalculator" failed: RET_CHECK failure (third_party/mediapipe/calculators/tensor/image_to_tensor_utils.cc:56) roi->width > 0 && roi->height > 0 ROI width and height must be > 0.; WaitUntilIdle failed Error: Encountered multiple errors: Adding proto packet of type mediapipe.NormalizedRect to stream norm_rect was not ok: $Graph has errors: Calculator::Process() for node "mediapipe_tasks_vision_pose_landmarker_poselandmarkergraph__mediapipe_tasks_vision_pose_detector_posedetectorgraph__mediapipe_tasks_components_processors_imagepreprocessinggraph__ImageToTensorCalculator" failed: RET_CHECK failure (third_party/mediapipe/calculators/tensor/image_to_tensor_utils.cc:56) roi->width > 0 && roi->height > 0 ROI width and height must be > 0., WaitUntilIdle failed: $CalculatorGraph::Run() failed in Run: Calculator::Process() for node "mediapipe_tasks_vision_pose_landmarker_poselandmarkergraph__mediapipe_tasks_vision_pose_detector_posedetectorgraph__mediapipe_tasks_components_processors_imagepreprocessinggraph__ImageToTensorCalculator" failed: RET_CHECK failure (third_party/mediapipe/calculators/tensor/image_to_tensor_utils.cc:56) roi->width > 0 && roi->height > 0 ROI width and height must be > 0.; WaitUntilIdle failed    at Wo (vendor.js:342873:22)     at Qh.finishProcessing (vendor.js:342934:32)     at Wa (vendor.js:343799:46)     at Ka (vendor.js:343807:3)     at Qh.G (vendor.js:344810:63)     at VideoEvaluationComponent.detectStomp (main.js:3475:45)     at main.js:2152:16    at Generator.next (<anonymous>)    at asyncGeneratorStep (vendor.js:398125:24)     at _next (vendor.js:398144:9)     at vendor.js:398149:7    at new ZoneAwarePromise (polyfills.js:8663:21)     at vendor.js:398141:12    at VideoEvaluationComponent.onVideoTimeUpdate (main.js:2156:7)     at VideoEvaluationComponent_Template_video_timeupdate_0_listener (main.js:3534:20)     at executeListenerWithErrorHandling (vendor.js:267650:12)     at wrapListenerIn_markDirtyAndPreventDefault (vendor.js:267681:18)     at HTMLVideoElement.<anonymous> (vendor.js:330674:34)     at _ZoneDelegate.invokeTask (polyfills.js:7662:171)     at vendor.js:277403:49    at AsyncStackTaggingZoneSpec.onInvokeTask (vendor.js:277403:30)     at _ZoneDelegate.invokeTask (polyfills.js:7662:54)     at Object.onInvokeTask (vendor.js:277705:25)     at _ZoneDelegate.invokeTask (polyfills.js:7662:54)     at Zone.runTask (polyfills.js:7467:37)     at ZoneTask.invokeTask [as invoke] (polyfills.js:7739:26)     at invokeTask (polyfills.js:8890:12)     at globalCallback (polyfills.js:8920:21)     at HTMLVideoElement.globalZoneAwareCallback (polyfills.js:8951:12)     at resolvePromise (polyfills.js:8451:19)     at polyfills.js:8360:9    at polyfills.js:8376:25    at asyncGeneratorStep (vendor.js:398128:5)     at _next (vendor.js:398144:9)     at vendor.js:398149:7    at new ZoneAwarePromise (polyfills.js:8663:21)     at vendor.js:398141:12    at VideoEvaluationComponent.onVideoTimeUpdate (main.js:2156:7)     at VideoEvaluationComponent_Template_video_timeupdate_0_listener (main.js:3534:20)     at executeListenerWithErrorHandling (vendor.js:267650:12)     at wrapListenerIn_markDirtyAndPreventDefault (vendor.js:267681:18)     at HTMLVideoElement.<anonymous> (vendor.js:330674:34)     at _ZoneDelegate.invokeTask (polyfills.js:7662:171)     at vendor.js:277403:49    at AsyncStackTaggingZoneSpec.onInvokeTask (vendor.js:277403:30)     at _ZoneDelegate.invokeTask (polyfills.js:7662:54)     at Object.onInvokeTask (vendor.js:277705:25)     at _ZoneDelegate.invokeTask (polyfills.js:7662:54)     at Zone.runTask (polyfills.js:7467:37)     at ZoneTask.invokeTask [as invoke] (polyfills.js:7739:26)     at invokeTask (polyfills.js:8890:12)     at globalCallback (polyfills.js:8920:21) at HTMLVideoElement.globalZoneAwareCallback (polyfills.js:8951:12)
```

**Comment by kuaashish** [comment]
Hi @janaki112,

We have a more recent version, [0.10.14](https://www.npmjs.com/package/@mediapipe/tasks-vision). Could you please try using the latest version and let us know if you still experience the same behavior?

Thank you!!

**Comment by janaki112** [comment]
> Hi @janaki112,
> 
> We have a more recent version, [0.10.14](https://www.npmjs.com/package/@mediapipe/tasks-vision). Could you please try using the latest version and let us know if you still experience the same behavior?
> 
> Thank you!!

ok Sure , i'll check and let you know
