### ISSUE TITLE
LLM_INFERENCE IN EMULATOR NOT WORKING

### ISSUE THREAD

**Issue by Nikhil34712** [google-ai-edge/mediapipe#5449]
### OS Platform and Distribution

ANDROID

### Programming Language and version

KOTLIN

### Android AAR (if android)

None

### Describe the problem

A bug happened!  Anyone Please solve this if you came across this When i tried to run the app in android studio i connected one virtual device to the android studio and when i ran the app the emulator is opening the mediapipe application and its showing loading model but after the app is crashing like its saying app is stopping 

### Complete Logs

```shell
FATAL EXCEPTION: main
                                                                                                    Process: com.google.mediapipe.examples.llminference, PID: 8548
                                                                                                    java.lang.UnsatisfiedLinkError: dlopen failed: library "libllm_inference_engine_jni.so" not found
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
                                                                                                    	at java.lang.System.loadLibrary(System.java:1664)
                                                                                                    	at com.google.mediapipe.tasks.genai.llminference.LlmInference.<clinit>(LlmInference.java:28)
                                                                                                    	at com.google.mediapipe.tasks.genai.llminference.LlmInference.createFromOptions(LlmInference.java:34)
                                                                                                    	at com.google.mediapipe.examples.llminference.InferenceModel.<init>(InferenceModel.kt:36)
                                                                                                    	at com.google.mediapipe.examples.llminference.InferenceModel.<init>(Unknown Source:0)
                                                                                                    	at com.google.mediapipe.examples.llminference.InferenceModel$Companion.getInstance(InferenceModel.kt:51)
                                                                                                    	at com.google.mediapipe.examples.llminference.LoadingScreenKt$LoadingRoute$2$1.invokeSuspend(LoadingScreen.kt:42)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
                                                                                                    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@4295de4, androidx.compose.runtime.BroadcastFrameClock@290a24d, StandaloneCoroutine{Cancelling}@d96c102, AndroidUiDispatcher@18afa13]
```

**Comment by kuaashish** [comment]
Hi @Nikhil34712,

Unfortunately, our GenAI Task APIs can not run on an emulator, as they are not designed for that environment. For more information, we recommend reviewing this thread https://github.com/google-ai-edge/mediapipe/issues/5362.

Thank you!!
