### ISSUE TITLE
createFromOptions throw error

### ISSUE THREAD

**Issue by ly15927086342** [google-ai-edge/mediapipe#5471]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

Yes

### OS Platform and Distribution

mac m1 14.5

### Browser and version if the issue happens on browser

chrome 125.0.6422.142

### Programming Language and version

javascript

### MediaPipe version

0.10.14

### Solution

every model

### Describe the actual behavior

when i use model.createFromOptions method, chrome throw error.

### Describe the expected behaviour

before i upgrade the chrome, it works well. I think the newest version of chrome has bug.

### Standalone code/steps you may have used to try to get what you need

```shell
it throws error like following:
main.js:329 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'body')
    at myFetch (main.js:329:25)
    at ic.l (vision_bundle.mjs:1:47151)
    at ic.l (vision_bundle.mjs:1:76591)
    at ic.o (vision_bundle.mjs:1:132370)
    at Zo (vision_bundle.mjs:1:45744)
    at async Xd.init (base.ts:30:27)
    at async getModelIns (index.ts:49:5)
    at async setModelName (index.ts:130:19)
    at async Proxy.mounted (video.vue:96:5)
I think the newest verison of chrome change the source code of fetch method, every get method with fetch all throw the same error.
```

**Comment by ly15927086342** [comment]
I find the reason is that I open a chrome plugin named Ajax Modifier. Close it, everything is ok.
