### ISSUE TITLE
Make android solutions(face detection) working with 'minifyEnabled true' build option.

### ISSUE THREAD

**Issue by farmaker47** [google-ai-edge/mediapipe#5486]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

No

### OS Platform and Distribution

Android 13

### Mobile device if the issue happens on mobile device

All devices

### Programming Language and version

Kotlin 1.9.23

### MediaPipe version

0.10.14

### Solution

Face Detector

### Describe the actual behavior

Project builds with minifyEnable true but Face detector fails to load model.

### Describe the expected behaviour

Builds, loads and uses model with minifyEnable = true

### Standalone code/steps you may have used to try to get what you need

```shell
The project I use is under NDA and in production and unfortunately I cannot share a link.
Steps are easy. Using FaceDetector simply change minifyEnable of the release version to true.
Solutions like this one:
https://github.com/google-ai-edge/mediapipe/issues/3509
do not work anymore. As a matter of fact the issue is not building but making it work.

Placing some logs I see that the initialization procedure fails as a runtimeexception here:


try {
            val optionsBuilder =
                FaceDetector.FaceDetectorOptions.builder()
                    .setBaseOptions(baseOptionsBuilder.build())
                    .setMinDetectionConfidence(threshold)
                    .setRunningMode(runningMode)

            when (runningMode) {
                RunningMode.IMAGE,
                RunningMode.VIDEO -> optionsBuilder.setRunningMode(runningMode)

                RunningMode.LIVE_STREAM ->
                    optionsBuilder.setRunningMode(runningMode)
                        .setResultListener(this::returnLivestreamResult)
                        .setErrorListener(this::returnLivestreamError)
            }

            val options = optionsBuilder.build()
            detector = FaceDetector.createFromOptions(context, options)
            Log.v(TAG, "Detector initialized.")
        } catch (e: IllegalStateException) {
            detectorListener?.onError(
                "Face detector failed to initialize. See error logs for details"
            )
            Log.v(TAG, "TFLite failed to load model with error1: " + e.message)
        } catch (e: RuntimeException) {
            detectorListener?.onError(
                "Face detector failed to initialize. See error logs for " +
                        "details", GPU_ERROR
            )
            Log.v(
                TAG,
                "Face detector failed to load model with error2: " + e.message
            )
        }
```

the proguard rules I use are:

```
-keep class javax.lang.model.** { *; }
-keep class autovalue.shaded.com.squareup.javapoet.** { *; }
-keep class okhttp3.internal.platform.** { *; }

-keep class com.google.mediapipe.solutioncore.** { *; }
-keep class com.google.protobuf.** { *; }

-dontwarn com.google.protobuf.**
-dontwarn javax.lang.model.**
-dontwarn okhttp3.internal.platform.**
```
```


### Other info / Complete Logs

```shell
The logs are:

"
Face detector failed to load model with error2: Field platform_ for w4.K not found. Known fields are [public static final w4.K w4.K.W, public static volatile com.google.protobuf.GeneratedMessageLite$DefaultInstanceBasedParser w4.K.X]

"
```

**Comment by erfansn** [comment]
These three rules worked for me:

```
-keep class com.google.mediapipe.proto.** { *; }
-keepclassmembers class * extends com.google.protobuf.GeneratedMessageLite { *; }
-keep class com.google.common.flogger.** { *; }
```

**Comment by farmaker47** [comment]
I can verify that the solution @erfansn provided also **works** in my project but I think this is a workaround rather than a solution for MediaPipe Facedetector task. I hope this issue stays open until they have a version that we do not have to apply rules in proguard file.

**Comment by kuaashish** [comment]
Hi @farmaker47,

We will keep the issue open until it is resolved. Additionally, we are sharing this with our team to ensure it remains on our radar. However, we cannot provide an exact timeline for the fix.

Thank you!!

**Comment by mimai-hen** [comment]
I have this issue too :-/

**Comment by kpatel-dinty** [comment]
I have the same exact issue as well. Here's my stack trace:

java.lang.ExceptionInInitializerError
                                                                                                    	at com.mynamespace.api.embedding.FaceDetectionOverlay$analyzer$1$3.invokeSuspend(FaceDetectionOverlay.java:177)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:100)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.java:586)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.java:829)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.java:717)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.java:704)
                                                                                                    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [a0{Cancelling}@82ec4d3, Dispatchers.Default]
                                                                                                    Caused by: java.lang.RuntimeException: Field platform_ for jf.d0 not found. Known fields are [public static final jf.d0 jf.d0.Y, public static volatile rf.v jf.d0.Z]
                                                                                                    	at com.google.protobuf.MessageSchema.reflectField(MessageSchema.java:621)
                                                                                                    	at rf.MessageSchema.reflectField(MessageSchema.java:0)
                                                                                                    	at com.google.protobuf.MessageSchema.newSchemaForRawMessageInfo(MessageSchema.java:508)
                                                                                                    	at com.google.protobuf.MessageSchema.newSchema(MessageSchema.java:227)
                     a                                                                               	at com.google.protobuf.ManifestSchemaFactory.newSchema(ManifestSchemaFactory.java:55)
                     a                                                                               	at com.google.protobuf.ManifestSchemaFactory.createSchema(ManifestSchemaFactory.java:49)
                     a                                                                               	at com.google.protobuf.Protobuf.schemaFor(Protobuf.java:68)
                                                                                                    	at com.google.protobuf.Protobuf.schemaFor(Protobuf.java:82)
                                                                                                    	at com.google.protobuf.GeneratedMessageLite.makeImmutable(GeneratedMessageLite.java:203)
                                                                                                    	at com.google.protobuf.GeneratedMessageLite$Builder.buildPartial(GeneratedMessageLite.java:484)
                                                                                                    	at com.google.protobuf.GeneratedMessageLite$Builder.build(GeneratedMessageLite.java:490)
                                                                                                    	at com.google.mediapipe.tasks.core.logging.TasksStatsProtoLogger.create(TasksStatsProtoLogger.java:119)
                                                                                                    	at com.google.mediapipe.tasks.core.TaskRunner.create(TaskRunner.java:59)
                                                                                                    	at com.google.mediapipe.tasks.vision.facedetector.FaceDetector.createFromOptions(FaceDetector.java:175)
                                                                                                    	at com.mynamespace.api.embedding.FacialDetectionUtils.<clinit>(FacialDetectionUtils.java:24)
                                                                                                    	... 4 more
