### ISSUE TITLE
ValidatedGraphConfig Initialization failed.

### ISSUE THREAD

**Issue by cgowthamanmca** [google-ai-edge/mediapipe#5493]
Hi I am facing this issue please any one help on this issue source code attched below

[Uploading mediapipe_face_detection_aar_example-master.zip…]()

  E0000 00:00:1718865162.913971    6164 graph.cc:482] ValidatedGraphConfig Initialization failed.
                                                                                                    No registered object with name: FaceGeometryEnvGeneratorCalculator; Unable to find Calculator "FaceGeometryEnvGeneratorCalculator"
                                                                                                    No registered object with name: SingleFaceSmoothLandmarkGpu; Unable to find Calculator "SingleFaceSmoothLandmarkGpu"
                                                                                                    No registered object with name: FaceGeometry; Unable to find Calculator "FaceGeometry"
                                                                                                    No registered object with name: FaceGeometryEffectRendererCalculator; Unable to find Calculator "FaceGeometryEffectRendererCalculator"
                                                                                                    No registered object with name: FaceGeometryEffectRendererCalculator; Unable to find Calculator "FaceGeometryEffectRendererCalculator"
                                                                                                    No registered object with name: ImmediateMuxCalculator; Unable to find Calculator "ImmediateMuxCalculator"
2024-06-20 12:02:42.914  6085-6164  GlThread                com.example.myfacedetectionapp       D  Stopping GL thread ExternalTextureConverter
2024-06-20 12:02:42.915  6085-6164  AndroidRuntime          com.example.myfacedetectionapp       E  FATAL EXCEPTION: ExternalTextureConverter
                                                                                                    Process: com.example.myfacedetectionapp, PID: 6085
                                                                                                    com.google.mediapipe.framework.MediaPipeException: not found: ValidatedGraphConfig Initialization failed.
                                                                                                    No registered object with name: FaceGeometryEnvGeneratorCalculator; Unable to find Calculator "FaceGeometryEnvGeneratorCalculator"
                                                                                                    No registered object with name: SingleFaceSmoothLandmarkGpu; Unable to find Calculator "SingleFaceSmoothLandmarkGpu"
                                                                                                    No registered object with name: FaceGeometry; Unable to find Calculator "FaceGeometry"
                                                                                                    No registered object with name: FaceGeometryEffectRendererCalculator; Unable to find Calculator "FaceGeometryEffectRendererCalculator"
                                                                                                    No registered object with name: FaceGeometryEffectRendererCalculator; Unable to find Calculator "FaceGeometryEffectRendererCalculator"
                                                                                                    No registered object with name: ImmediateMuxCalculator; Unable to find Calculator "ImmediateMuxCalculator"
                                                                                                    	at com.google.mediapipe.framework.Graph.nativeStartRunningGraph(Native Method)
                                                                                                    	at com.google.mediapipe.framework.Graph.startRunningGraph(Graph.java:343)
                                                                                                    	at com.google.mediapipe.components.FrameProcessor.startGraph(FrameProcessor.java:553)
                                                                                                    	at com.google.mediapipe.components.FrameProcessor.maybeAcceptNewFrame(FrameProcessor.java:421)
                                                                                                    	at com.google.mediapipe.components.FrameProcessor.onNewFrame(FrameProcessor.java:439)
                                                                                                    	at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.renderNext(ExternalTextureConverter.java:485)
                                                                                                    	at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.lambda$onFrameAvailable$0$com-google-mediapipe-components-ExternalTextureConverter$RenderThread(ExternalTextureConverter.java:413)
                                                                                                    	at com.google.mediapipe.components.ExternalTextureConverter$RenderThread$$ExternalSyntheticLambda1.run(Unknown Source:4)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205)
                                                                                                    	at android.os.Looper.loop(Looper.java:294)
                                                                                                    	at com.google.mediapipe.glutil.GlThread.run(GlThread.java:146)

**Comment by kuaashish** [comment]
Hi @cgowthamanmca,

Could you please provide the complete steps you are following from our documentation? It appears you are using the legacy face detection solution and trying the AAR example. If so, please switch to the new Face Detection Task API using the Maven package for Android implementation. You can find the updated documentation for the Face Detection Task API [here](https://ai.google.dev/edge/mediapipe/solutions/vision/face_detector) and the Android implementation [here](hhttps://ai.google.dev/edge/mediapipe/solutions/vision/face_detector/android). Please note that we are no longer maintaining the app-building process through AAR.

Thank you for your understanding.

**Comment by cgowthamanmca** [comment]
@kuaashish can you please share any example for like face effect

**Comment by kuaashish** [comment]
Hi @cgowthamanmca,

Please allow us some time to discuss with our team. We will update you on the status.

**Comment by kuaashish** [comment]
Hi @kostyaby,

We are having difficulty finding an example for face effects using our new Task API. This feature was available in our legacy solution. Could you provide some guidance on how to achieve this with the new Task API? Your assistance would greatly benefit the community.

Thank  you!!

**Comment by kostyaby** [comment]
Unfortunately, there is no example for that and I'm not even sure the Tasks API propagates all the correct right information back into the user level to achieve this. Think of Tasks API as a more polished/predictable, but a more limited version of the legacy Solutions API. It was intended / designed that it doesn't necessarily provide all the features from a legacy, less robust solution

**Comment by kuaashish** [comment]
Hi @cgowthamanmca,

Please review the above comment. We apologize, but the new Task API does not include this feature. If you need this feature, please use our legacy method. If you encounter any further issues, we will do our best to assist you, If we have bandwidth.

Thank you!!
