### ISSUE TITLE
selfie_multiclass task  with option delegate=BaseOptions.Delegate.GPU not working

### ISSUE THREAD

**Issue by SoaringTiger** [google-ai-edge/mediapipe#5503]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

Ubuntu 22.04.3 LTS (docker image: tensorflow:2.16.1-gpu-jupyter)

### MediaPipe Tasks SDK version

 0.10.14

### Task name (e.g. Image classification, Gesture recognition etc.)

selfie_multiclass

### Programming Language and version (e.g. C++, Python, Java)

Python

### Describe the actual behavior

delegate=BaseOptions.Delegate.GPU  not work

### Describe the expected behaviour

enable GPU support

### Standalone code/steps you may have used to try to get what you need

```shell
import mediapipe as mp
import numpy as np
import cv2

model_path = '/models/mediapipe/selfie_multiclass_256x256.tflite'

IMAGE_FILE = 'input.jpg'

BaseOptions = mp.tasks.BaseOptions
ImageSegmenter = mp.tasks.vision.ImageSegmenter
ImageSegmenterOptions = mp.tasks.vision.ImageSegmenterOptions
VisionRunningMode = mp.tasks.vision.RunningMode


# ImageSegmenter 
options = ImageSegmenterOptions(
    #base_options=BaseOptions(model_asset_path=model_path),
    base_options = BaseOptions(model_asset_path=model_path, delegate=BaseOptions.Delegate.GPU),
    running_mode=VisionRunningMode.IMAGE,
    output_category_mask=True)

colors = [
    [255, 0, 0],  # background: blue
    [255, 255, 0],  # hair: skyblue
    [0, 255, 0],  # body-skin: green
    [255, 0, 128],  # face-skin: purple
    [255, 0, 255],  # clothes: magenta
    [0, 128, 255]  # others: orange
]

category = ["background", "hair", "body-skin", "face-skin", "clothes", "others"]


with ImageSegmenter.create_from_options(options) as segmenter:

    mp_image = mp.Image.create_from_file(IMAGE_FILE)

    original_image = mp_image.numpy_view()
    # original_image = original_image[:, :, :3]  # remove alpha channel

    # masks
    segmented_masks = segmenter.segment(mp_image)

    # category_mask
    category_mask = segmented_masks.category_mask
    category_mask_np = category_mask.numpy_view()

    h, w = category_mask_np.shape # numpy  width, height 
    color_image = np.zeros((h, w, 3), dtype=np.uint8) #generate same size empty image
    for i, color in enumerate(colors): # fill every class
        color_image[category_mask_np == i] = color

    alpha = 0.5
    blended_image = cv2.addWeighted(original_image, 1 - alpha, color_image, alpha, 0)

    status = cv2.imwrite('path_to_save_image.jpg', blended_image)
    print("Image written to file-system: ", status)
```

### Other info / Complete Logs

```shell
When I set base_options=BaseOptions(model_asset_path=model_path), the code worked, when I set base_options = BaseOptions(model_asset_path=model_path, delegate=BaseOptions.Delegate.GPU), the code got error:
'''
2024-06-25 02:26:50.945231: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1719282412.338260     551 task_runner.cc:85] GPU suport is not available: INTERNAL: ; RET_CHECK failure (mediapipe/gpu/gl_context_egl.cc:77) display != EGL_NO_DISPLAYeglGetDisplay() returned error 0x300c
Traceback (most recent call last):
  File "/tools/mask_1_img.py", line 37, in <module>
    with ImageSegmenter.create_from_options(options) as segmenter:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/mediapipe/tasks/python/vision/image_segmenter.py", line 268, in create_from_options
    return cls(
           ^^^^
  File "/usr/local/lib/python3.11/dist-packages/mediapipe/tasks/python/vision/image_segmenter.py", line 145, in __init__
    super(ImageSegmenter, self).__init__(
  File "/usr/local/lib/python3.11/dist-packages/mediapipe/tasks/python/vision/core/base_vision_task_api.py", line 70, in __init__
    self._runner = _TaskRunner.create(graph_config, packet_callback)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Service "kGpuService", required by node mediapipe_tasks_vision_image_segmenter_imagesegmentergraph__mediapipe_tasks_core_inferencesubgraph__inferencecalculator__mediapipe_tasks_vision_image_segmenter_imagesegmentergraph__mediapipe_tasks_core_inferencesubgraph__InferenceCalculator, was not provided and cannot be created: ; RET_CHECK failure (mediapipe/gpu/gl_context_egl.cc:77) display != EGL_NO_DISPLAYeglGetDisplay() returned error 0x300c
'''

run the script in tensorflow:2.16.1-gpu-jupyter container
import tensorflow as tf
print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))

'''
>>> import tensorflow as tf
2024-06-25 03:53:58.671721: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
>>> print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))
2024-06-25 03:54:00.062634: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:998] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-06-25 03:54:00.067000: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:998] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-06-25 03:54:00.067152: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:998] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
Num GPUs Available:  1
'''
```

**Comment by kuaashish** [comment]
Hi @SoaringTiger,

Thank you for bringing this to our attention again. It appears that our multi-class selfie segmentation currently does not support GPU usage. A similar issue was reported previously at https://github.com/google-ai-edge/mediapipe/issues/5081. Please allow us some time to investigate further, and I will provide an update soon.

Thank you!!

**Comment by kuaashish** [comment]
Hi @SoaringTiger,

Could you confirm if you can run other examples in your GPU environment, such as the Hand example provided [here](https://colab.sandbox.google.com/github/googlesamples/mediapipe/blob/main/examples/hand_landmarker/python/hand_landmarker.ipynb)?

Thank you!!

**Comment by SoaringTiger** [comment]
> Hi @SoaringTiger,
> 
> Could you confirm if you can run other examples in your GPU environment, such as the Hand example provided [here](https://colab.sandbox.google.com/github/googlesamples/mediapipe/blob/main/examples/hand_landmarker/python/hand_landmarker.ipynb)?
> 
> Thank you!!

Hi @kuaashish

```
# STEP 2: Create an HandLandmarker object.
base_options = python.BaseOptions(
    model_asset_path='/models/mediapipe/hand_landmarker.task', 
    #delegate=BaseOptions.Delegate.GPU
    )
options = vision.HandLandmarkerOptions(base_options=base_options,
                                       num_hands=2)
detector = vision.HandLandmarker.create_from_options(options)
```

When I run the code without GPU, got warning, but I can get result image: 
```
I0000 00:00:1720067300.162163     406 task_runner.cc:85] GPU suport is not available: INTERNAL: ; RET_CHECK failure (mediapipe[/gpu/gl_context_egl.cc:77](http://192.168.2.8:8888/gpu/gl_context_egl.cc#line=76)) display != EGL_NO_DISPLAYeglGetDisplay() returned error 0x300c
W0000 00:00:1720067300.170902     948 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1720067300.186529     948 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
```

When I run the code with 'delegate=BaseOptions.Delegate.GPU', I got error: 

```
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1720067775.707569    1064 task_runner.cc:85] GPU suport is not available: INTERNAL: ; RET_CHECK failure (mediapipe/gpu/gl_context_egl.cc:77) display != EGL_NO_DISPLAYeglGetDisplay() returned error 0x300c
Traceback (most recent call last):
  File "/sam/mp_mask_1_hands.py", line 65, in <module>
    detector = vision.HandLandmarker.create_from_options(options)
  File "/usr/local/lib/python3.10/dist-packages/mediapipe/tasks/python/vision/hand_landmarker.py", line 364, in create_from_options
    return cls(
  File "/usr/local/lib/python3.10/dist-packages/mediapipe/tasks/python/vision/core/base_vision_task_api.py", line 70, in __init__
    self._runner = _TaskRunner.create(graph_config, packet_callback)
RuntimeError: Service "kGpuService", required by node mediapipe_tasks_vision_hand_landmarker_handlandmarkergraph__mediapipe_tasks_vision_hand_detector_handdetectorgraph__mediapipe_tasks_core_inferencesubgraph__inferencecalculator__mediapipe_tasks_vision_hand_landmarker_handlandmarkergraph__mediapipe_tasks_vision_hand_detector_handdetectorgraph__mediapipe_tasks_core_inferencesubgraph__InferenceCalculator, was not provided and cannot be created: ; RET_CHECK failure (mediapipe/gpu/gl_context_egl.cc:77) display != EGL_NO_DISPLAYeglGetDisplay() returned error 0x300c
```

**Comment by kuaashish** [comment]
Hi @SoaringTiger,

It seems that some drivers are missing, preventing the GPU from being detected in the environment. Can you please try this Colab for benchmarking some of the tasks: [Colab Notebook](https://colab.research.google.com/gist/kinarr/e9c7d99eef33c1c3a9f596b74f491f50/-10-31-23-mediapipe-tasks-gpu-support-benchmark.ipynb)? Additionally, could you adopt the same for your environment and update us on the status?

Thank you!!

**Comment by SoaringTiger** [comment]
> Hi @SoaringTiger,
> 
> It seems that some drivers are missing, preventing the GPU from being detected in the environment. Can you please try this Colab for benchmarking some of the tasks: [Colab Notebook](https://colab.research.google.com/gist/kinarr/e9c7d99eef33c1c3a9f596b74f491f50/-10-31-23-mediapipe-tasks-gpu-support-benchmark.ipynb)? Additionally, could you adopt the same for your environment and update us on the status?
> 
> Thank you!!

my nvidia-smi info in docker container, docker image is tensorflow/tensorflow:2.16.2-gpu-jupyter
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 545.29.06              Driver Version: 545.29.06    CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 4060 Ti     Off | 00000000:01:00.0  On |                  N/A |
|  0%   52C    P8               8W / 165W |  14558MiB / 16380MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

I have install the mediapipe-nightly and I can only run mediapipe task script without gpu option:  [colab](https://colab.research.google.com/gist/kinarr/e9c7d99eef33c1c3a9f596b74f491f50/-10-31-23-mediapipe-tasks-gpu-support-benchmark.ipynb)

I have tested tensorflow with gpu in container
```
import tensorflow as tf

print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))

matrix1 = tf.random.uniform([1000, 1000])
matrix2 = tf.random.uniform([1000, 1000])

with tf.device('/GPU:0'):
    product = tf.matmul(matrix1, matrix2)

with tf.device('/GPU:0'):
    print("Matrix multiplication result on GPU:")
    print(product)
```
Got result
```
Num GPUs Available:  1
Matrix multiplication result on GPU:
tf.Tensor(
[[243.63484 238.3081  250.76256 ... 249.20293 241.33276 251.67079]
 [249.44817 234.74933 245.9238  ... 242.76912 239.75523 247.66855]
 [238.73503 231.70839 242.5265  ... 243.06746 235.40015 246.4232 ]
 ...
 [236.47717 229.38445 241.08224 ... 236.93318 233.91486 245.26237]
 [246.1244  242.03398 246.94525 ... 250.89856 238.61884 247.93216]
 [248.92546 240.55031 253.50462 ... 248.77428 250.05797 252.9958 ]], shape=(1000, 1000), dtype=float32)
```

**Comment by kuaashish** [comment]
Hi @kinarr,

Could you please assist with resolving the issue of not being able to utilize the GPU in the Docker environment?

Thank you!!

**Comment by ErikValle2** [comment]
I have exactly the same setup and erros as this issue, but using FaceLandmarker. Looking forward to hearing back from you guys.

**Comment by Utkarsh-shift** [comment]
Same issue downgrade your media pipe from 10 to 9

**Comment by ErikValle2** [comment]
> I have exactly the same setup and erros as this issue, but using FaceLandmarker. Looking forward to hearing back from you guys.
> 
> **Error prompt:**
> 
> ```shell
> File "/usr/local/lib/python3.11/dist-packages/mediapipe/tasks/python/vision/face_landmarker.py", line 3104, in create_from_options
>     return cls(
>            ^^^^
>   File "/usr/local/lib/python3.11/dist-packages/mediapipe/tasks/python/vision/core/base_vision_task_api.py", line 70, in __init__
>     self._runner = _TaskRunner.create(graph_config, packet_callback)
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> RuntimeError: Service "kGpuService", required by node mediapipe_tasks_vision_face_landmarker_facelandmarkergraph__mediapipe_tasks_vision_face_detector_facedetectorgraph__mediapipe_tasks_core_inferencesubgraph__inferencecalculator__mediapipe_tasks_vision_face_landmarker_facelandmarkergraph__mediapipe_tasks_vision_face_detector_facedetectorgraph__mediapipe_tasks_core_inferencesubgraph__InferenceCalculator, was not provided and cannot be created: ; RET_CHECK failure (mediapipe/gpu/gl_context_egl.cc:84) egl_initializedUnable to initialize EGL
> ```
About FaceLandmarker:
`Face blendshape model contains CPU only ops. Sets FaceBlendshapesGraph acceleration to Xnnpack.`
It means **not all models were modified to support GPU processing**. In this case, the [documentation](https://ai.google.dev/edge/mediapipe/solutions/vision/face_landmarker) mentions that only the face detector (BlazeFace short-range) bundled to FaceLandmarker is optimized for GPU inference. Therefore, **I recommend you to check the model cards first to verify if it does support GPU.**

**Comment by richtertang** [comment]
**The root cause is EGL display initialization — same issue as #2489, but on x86/NVIDIA Docker.**

Looking at the error:

I0000 00:00:... task_runner.cc:85] GPU suport is not available: INTERNAL: ; RET_CHECK failure (mediapipe/gpu/gl_context_egl.cc:77) display != EGL_NO_DISPLAY eglGetDisplay() returned EGL_NO_DISPLAY


This tells us `eglGetDisplay(EGL_DEFAULT_DISPLAY)` is returning `EGL_NO_DISPLAY` inside your Docker container. This is the **same architectural problem** that affects headless ARM Mali systems (see #2489):

- `eglGetDisplay()` without an explicit platform relies on the EGL implementation's default behavior
- Inside Docker (no X11 socket, no DISPLAY), there's no default display for EGL to find
- MediaPipe's `gl_context_egl.cc` line 77 does `RET_CHECK(display != EGL_NO_DISPLAY)` → crash

#### What's happening in your container

TensorFlow can see the GPU via CUDA (`tf.config.list_physical_devices('GPU')` returns 1), but **MediaPipe doesn't use CUDA for GPU inference** — it uses OpenGL ES via EGL. The CUDA-visible GPU doesn't automatically give you an EGL display. You need either:

1. **X11 socket passthrough** into Docker (bind-mount `/tmp/.X11-unix` + set `DISPLAY`) — works but adds X11 dependency
2. **NVIDIA EGL Device extension** (`EGL_EXT_platform_device`) — query EGL devices directly via `eglGetPlatformDisplay(EGL_PLATFORM_DEVICE_EXT, device_index, NULL)`, no X11 needed. This is what `nvidia-driver` provides via `/usr/share/glvnd/egl_vendor.d/10_nvidia.json`

#### Our experience solving this on ARM Mali

We ran into the identical `eglGetDisplay() → EGL_NO_DISPLAY` problem on ARM headless (Rockchip RK3576, Mali-G52, no X server). Our fix was to replace `eglGetDisplay()` with `eglGetPlatformDisplay(EGL_PLATFORM_GBM_KHR, ...)` + a surface workaround (since GBM doesn't support pbuffers).

For your x86/NVIDIA Docker case, the equivalent fix would be `eglGetPlatformDisplay(EGL_PLATFORM_DEVICE_EXT, ...)` — NVIDIA's EGL implementation supports this extension for headless GPU access.

We have **not tested this on NVIDIA/x86** (our verified platform is ARM Mali only), but the EGL initialization architecture is the same problem.

#### Quick workaround you can try right now

If you just need GPU working in Docker ASAP without patching MediaPipe:

```bash
# Option A: Xvfb inside container
apt-get install -y xvfb
Xvfb :1 -screen 0 1024x768x24 &
export DISPLAY=:1
python your_script.py

# Option B: X11 socket from host (if host has X)
docker run -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=$DISPLAY ...
```

####  Both are workarounds — the real fix should be in gl_context_egl.cc to probe available EGL platforms systematically.

Benchmark for reference (ARM Mali, headless GPU)
For anyone interested in headless GPU performance numbers, here's what we measured on RK3576 (Mali-G52) with our GBM patch:

Config	FaceLandmarker avg/frame	Speedup
CPU headless	33.4 ms	1.0x
GPU GBM headless	14.4 ms	2.3x
We're working on a comprehensive patch for gl_context_egl.cc to support multiple EGL platforms (GBM, Device, X11) with auto-detection. Would be happy to collaborate or share findings.

**Comment by gkarpiak** [comment]
@richtertang thanks for the thorough analysis!

@SoaringTiger could you please try the suggested workaround to see if it works or not for you?

It might work as a workaround for you while we are looking at the proper fix.
