### ISSUE TITLE
Pose solution intermittently aborts failing to grow heap to 60MB from 50MB

### ISSUE THREAD

**Issue by sivnag** [google-ai-edge/mediapipe#5549]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

Yes

### OS Platform and Distribution

Windows 10 CEF ( Chromium 101.0.4951.54 ) based c++ app. Mediapipe javascript solution runs inside embedded chromium browser tab.

### MediaPipe version

@mediapipe/pose v0.5.1635988162

### Solution

Pose

### Programming Language and version

javascript

### Describe the actual behavior

Running pose estimation with image segmentation ON from a web worker.
For some customer running my code, very rarely the solution works initially and eventually stops working, due to failure in growing the heap (when the target heap size was barely 60MB)
There are also occurrences of packet type mismatch in graph calculator after this heap error.
I am unable to reproduce the problem in my setup.

### Describe the expected behaviour

Pose estimation should not fail when heap memory is grown to such small target size
Some documentation on correct way to intercept this error (for example: adding ".catch(...)" to Pose.send(...) ) and recover from there (for example: calling .close() and then re-instantiating the solution etc.)
Some documentation on supplying a larger Heap from my code or specifying a larger heap size instead of using the default heap

### Other info / Complete Logs
...
[2024-04-16 14:39:50.204668] [0x00000cec] (warning) : JS : (pose_solution_simd_wasm_bin.js:9) : emscripten_realloc_buffer: Attempted to grow heap from 50331648 bytes to 60424192 bytes, but got error: RangeError: WebAssembly.Memory.grow(): Unable to grow instance memory
[2024-04-16 14:39:50.430435] [0x00000cec] (warning) : JS : (pose_solution_simd_wasm_bin.js:9) : emscripten_realloc_buffer: Attempted to grow heap from 50331648 bytes to 55377920 bytes, but got error: RangeError: WebAssembly.Memory.grow(): Unable to grow instance memory
[2024-04-16 14:39:50.671366] [0x00000cec] (warning) : JS : (pose_solution_simd_wasm_bin.js:9) : emscripten_realloc_buffer: Attempted to grow heap from 50331648 bytes to 52887552 bytes, but got error: RangeError: WebAssembly.Memory.grow(): Unable to grow instance memory
[2024-04-16 14:39:50.672414] [0x00000cec] (warning) : JS : (pose_solution_simd_wasm_bin.js:9) : Failed to grow the heap from 50331648 bytes to 52887552 bytes, not enough memory!
[2024-04-16 14:39:50.720497] [0x00000cec] (warning) : JS : (pose_solution_simd_wasm_bin.js:9) : emscripten_realloc_buffer: Attempted to grow heap from 50331648 bytes to 60424192 bytes, but got error: RangeError: WebAssembly.Memory.grow(): Unable to grow instance memory
[2024-04-16 14:39:50.988495] [0x00000cec] (warning) : JS : (pose_solution_simd_wasm_bin.js:9) : emscripten_realloc_buffer: Attempted to grow heap from 50331648 bytes to 55377920 bytes, but got error: RangeError: WebAssembly.Memory.grow(): Unable to grow instance memory
[2024-04-16 14:39:51.272358] [0x00000cec] (warning) : JS : (pose_solution_simd_wasm_bin.js:9) : emscripten_realloc_buffer: Attempted to grow heap from 50331648 bytes to 52887552 bytes, but got error: RangeError: WebAssembly.Memory.grow(): Unable to grow instance memory
[2024-04-16 14:39:51.272871] [0x00000cec] (warning) : JS : (pose_solution_simd_wasm_bin.js:9) : Failed to grow the heap from 50331648 bytes to 52887552 bytes, not enough memory!
[2024-04-16 14:39:51.272871] [0x00000cec] (warning) : JS : (pose_solution_simd_wasm_bin.js:9) : undefined
[2024-04-16 14:39:51.275804] [0x00000cec] (error) : JS : (pose_solution_simd_wasm_bin.js:9) : Uncaught (in promise) RuntimeError: abort(undefined) at Error
    at jsStackTrace (https://cdn.jsdelivr.net/npm/@mediapipe/pose@0.5.1635988162/pose_solution_simd_wasm_bin.js:9:69360)
    at stackTrace (https://cdn.jsdelivr.net/npm/@mediapipe/pose@0.5.1635988162/pose_solution_simd_wasm_bin.js:9:69536)
    at abort (https://cdn.jsdelivr.net/npm/@mediapipe/pose@0.5.1635988162/pose_solution_simd_wasm_bin.js:9:43094)
    at _abort (https://cdn.jsdelivr.net/npm/@mediapipe/pose@0.5.1635988162/pose_solution_simd_wasm_bin.js:9:180745)
    at https://cdn.jsdelivr.net/npm/@mediapipe/pose@0.5.1635988162/pose_solution_simd_wasm_bin.wasm:wasm-function[8364]:0x5754d8
    at https://cdn.jsdelivr.net/npm/@mediapipe/pose@0.5.1635988162/pose_solution_simd_wasm_bin.wasm:wasm-function[4893]:0x36ddba
    at https://cdn.jsdelivr.net/npm/@mediapipe/pose@0.5.1635988162/pose_solution_simd_wasm_bin.wasm:wasm-function[5622]:0x3c7f3c
    at https://cdn.jsdelivr.net/npm/@mediapipe/pose@0.5.1635988162/pose_solution_simd_wasm_bin.wasm:wasm-function[5621]:0x3c7de4
    at https://cdn.jsdelivr.net/npm/@mediapipe/pose@0.5.1635988162/pose_solution_simd_wasm_bin.wasm:wasm-function[4884]:0x36dbd3
    at https://cdn.jsdelivr.net/npm/@mediapipe/pose@0.5.1635988162/pose_solution_simd_wasm_bin.wasm:wasm-function[1213]:0x5b5c5

...
[2024-04-16 14:41:55.844800] [0x00000cec] (warning) : JS : (pose_solution_simd_wasm_bin.js:9) : E0416 14:41:55.833000       1 solutions_wasm.embind.cc:676] Adding to input_frames_gpu was not ok: INTERNAL: Graph has errors: 
[2024-04-16 14:41:55.844800] [0x00000cec] (warning) : JS : (pose_solution_simd_wasm_bin.js:9) : Packet type mismatch on a calculator receiving from stream "input_frames_gpu": Expected a Packet of type: drishti::GpuBuffer, but received an empty Packet. [type.googleapis.com/mediapipe.StatusList='\n\xa0\x01\x08\r\x12\x9b\x01Packet type mismatch on a calculator receiving from stream \"input_frames_gpu\": Expected a Packet of type: drishti::GpuBuffer, but received an empty Packet.']
[2024-04-16 14:41:55.844800] [0x00000cec] (warning) : JS : (pose_solution_simd_wasm_bin.js:9) : === Source Location Trace: === 
[2024-04-16 14:41:55.844800] [0x00000cec] (warning) : JS : (pose_solution_simd_wasm_bin.js:9) : third_party/mediapipe/framework/tool/status_util.cc:139
[2024-04-16 14:41:55.875090] [0x00000cec] (warning) : JS : (pose_solution_simd_wasm_bin.js:9) : emscripten_realloc_buffer: Attempted to grow heap from 50331648 bytes to 60424192 bytes, but got error: RangeError: WebAssembly.Memory.grow(): Unable to grow instance memory
[2024-04-16 14:41:56.067443] [0x00000cec] (warning) : JS : (pose_solution_simd_wasm_bin.js:9) : emscripten_realloc_buffer: Attempted to grow heap from 50331648 bytes to 55377920 bytes, but got error: RangeError: WebAssembly.Memory.grow(): Unable to grow instance memory
[2024-04-16 14:41:56.269337] [0x00000cec] (warning) : JS : (pose_solution_simd_wasm_bin.js:9) : emscripten_realloc_buffer: Attempted to grow heap from 50331648 bytes to 52887552 bytes, but got error: RangeError: WebAssembly.Memory.grow(): Unable to grow instance memory
[2024-04-16 14:41:56.270205] [0x00000cec] (warning) : JS : (pose_solution_simd_wasm_bin.js:9) : Failed to grow the heap from 50331648 bytes to 52887552 bytes, not enough memory!
[2024-04-16 14:41:56.270205] [0x00000cec] (warning) : JS : (pose_solution_simd_wasm_bin.js:9) : [low_level_alloc.cc : 588] RAW: mmap error: 48
[2024-04-16 14:41:56.270205] [0x00000cec] (warning) : JS : (pose_solution_simd_wasm_bin.js:9) : undefined
[2024-04-16 14:41:56.271202] [0x00000cec] (error) : JS : (pose_solution_simd_wasm_bin.js:9) : Uncaught (in promise) RuntimeError: abort(undefined) at Error
    at jsStackTrace (https://cdn.jsdelivr.net/npm/@mediapipe/pose@0.5.1635988162/pose_solution_simd_wasm_bin.js:9:69360)
    at stackTrace (https://cdn.jsdelivr.net/npm/@mediapipe/pose@0.5.1635988162/pose_solution_simd_wasm_bin.js:9:69536)
    at abort (https://cdn.jsdelivr.net/npm/@mediapipe/pose@0.5.1635988162/pose_solution_simd_wasm_bin.js:9:43094)
    at _abort (https://cdn.jsdelivr.net/npm/@mediapipe/pose@0.5.1635988162/pose_solution_simd_wasm_bin.js:9:180745)
    at https://cdn.jsdelivr.net/npm/@mediapipe/pose@0.5.1635988162/pose_solution_simd_wasm_bin.wasm:wasm-function[7746]:0x55088d
    at https://cdn.jsdelivr.net/npm/@mediapipe/pose@0.5.1635988162/pose_solution_simd_wasm_bin.wasm:wasm-function[7644]:0x5426c1
    at https://cdn.jsdelivr.net/npm/@mediapipe/pose@0.5.1635988162/pose_solution_simd_wasm_bin.wasm:wasm-function[7591]:0x5370f0
    at https://cdn.jsdelivr.net/npm/@mediapipe/pose@0.5.1635988162/pose_solution_simd_wasm_bin.wasm:wasm-function[7599]:0x537a75
    at https://cdn.jsdelivr.net/npm/@mediapipe/pose@0.5.1635988162/pose_solution_simd_wasm_bin.wasm:wasm-function[7598]:0x537a01
    at https://cdn.jsdelivr.net/npm/@mediapipe/pose@0.5.1635988162/pose_solution_simd_wasm_bin.wasm:wasm-function[5179]:0x38ac74
...

**Comment by sivnag** [comment]
My teammate mentioned that, sometimes overflow/corruption of call-stack can trigger unrelated errors such as failure in heap growth. Not sure if that can be true but wanted to ask here to clarify.
Can I request the solution for a larger stack size and larger heap size from my code?

**Comment by kuaashish** [comment]
Hi @sivnag,

After reviewing the provided standalone code, it appears that you are currently using the legacy Pose solution, which is no longer maintained, and we have ceased support for it. This functionality has been integrated into the new Pose Landmarker Task API, detailed [here](https://developers.google.com/mediapipe/solutions/guide#legacy).

We encourage you to explore the features of our updated Pose Landmarker Task API and suggest replacing the legacy Pose with the new Pose Landmarker. The new solution offers improved performance and additional functionality compared to the legacy Pose solution. You can find the guide for the new Pose Landmarker [here](https://ai.google.dev/edge/mediapipe/solutions/vision/pose_landmarker), along with specific instructions for implementation in the JavaScript platform provided [here](https://ai.google.dev/edge/mediapipe/solutions/vision/pose_landmarker/web_js). Additionally, a corresponding npm package for new Task API can be found [here](https://www.npmjs.com/package/@mediapipe/tasks-vision). 

Please report any observed behavior, ensuring to check if similar issues persist in the upgraded task API. Unfortunately, beyond this, there is limited action we can take to address the specific issue you are facing.

Thank you!!
