### ISSUE TITLE
Selective RegionOfInterest isn't available in FaceLandmarker task

### ISSUE THREAD

**Issue by RandomUserUsingGitHub** [google-ai-edge/mediapipe#5584]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

windows 10 / Web

### Task name (e.g. Image classification, Gesture recognition etc.)

FaceLandmarker

### Programming Language and version (e.g. C++, Python, Java)

JS / TypeScript

### Describe the actual behavior

I can't pass region of interest as a value to detectForVideo function

### Describe the expected behaviour

I need to crop my htmlVideoElement with the selective ROI option

### Standalone code/steps you may have used to try to get what you need

```shell
this.videoCut = {
      'left': left,
      'top': top,
      'right': right,
      'bottom': bottom
    }

const results = await this.faceLandMarker.detectForVideo(video, performance.now(), {regionOfInterest: this.videoCut});
```

### Other info / Complete Logs

```shell
detector.component.ts:244 ERROR Error: This task doesn't support region-of-interest.
    at th (vision_bundle.mjs:3303:24)
    at nh (vision_bundle.mjs:3326:3)
    at yh.G (vision_bundle.mjs:3440:22)
    at _DetectorComponent.<anonymous> (detector.component.ts:200:51)
    at Generator.next (<anonymous>)
    at main.js:18:61
    at new ZoneAwarePromise (zone.js:2702:25)
    at __async (main.js:2:10)
    at detect (detector.component.ts:174:31)
    at timer (zone.js:1809:37)
```

**Comment by RandomUserUsingGitHub** [comment]
ahhh my bad :D

**Comment by akashvverma1995** [comment]
Hi @RandomUserUsingGitHub 

Since the `FaceLandmarker` API doesn't support ROI natively, the standard workaround in a web/JS environment is to **manually crop the video frame using an HTML5 Canvas** *before* passing the data to MediaPipe.

I have tested this approach on my end and attached the reference code below. I hope you find this helpful! Please let us know if you have any further questions.

```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>MediaPipe Face Landmarker with ROI</title>
  <style>
    body { font-family: Arial, sans-serif; display: flex; flex-direction: column; align-items: center; background-color: #f5f5f5; margin-top: 40px;}
    .container { position: relative; display: inline-block; margin-bottom: 20px;}
    video { border: 1px solid #ccc; border-radius: 8px; background: #000; }
    #overlayCanvas { position: absolute; left: 0; top: 0; pointer-events: none; }
    #cropCanvas { border: 1px solid #ccc; border-radius: 8px; background: #fff;}
    .status { margin-bottom: 20px; font-weight: bold; color: #333; }
  </style>
</head>
<body>
  <h1>Face Landmarker with Region of Interest</h1>
  <p>The blue box is the fixed ROI. The smaller canvas below shows the cropped frame that is actually sent to MediaPipe.</p>
  <div class="status" id="status">Loading Face Landmarker Model...</div>
  
  <div class="container">
    <!-- Main Webcam feed -->
    <video id="webcam" autoplay playsinline width="640" height="480"></video>
    <!-- Overlay for drawing bounding boxes and remapped landmarks -->
    <canvas id="overlayCanvas" width="640" height="480"></canvas>
  </div>
  
  <h3>Cropped Frame (Sent to Model)</h3>
  <canvas id="cropCanvas"></canvas>

  <script type="module">
    import {
      FaceLandmarker,
      FilesetResolver
    } from "https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.35";

    const video = document.getElementById("webcam");
    const overlayCanvas = document.getElementById("overlayCanvas");
    const overlayCtx = overlayCanvas.getContext("2d");
    const cropCanvas = document.getElementById("cropCanvas");
    const cropCtx = cropCanvas.getContext("2d");
    const statusDiv = document.getElementById("status");

    let faceLandmarker;
    let lastVideoTime = -1;

    // Define ROI (Center of the 640x480 video)
    const roiLeft = 160;
    const roiTop = 120;
    const roiRight = 480;
    const roiBottom = 360;
    const roiWidth = roiRight - roiLeft;
    const roiHeight = roiBottom - roiTop;

    cropCanvas.width = roiWidth;
    cropCanvas.height = roiHeight;

    async function initializeMediaPipe() {
      // Load the vision tasks WASM
      const filesetResolver = await FilesetResolver.forVisionTasks(
        "https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.35/wasm"
      );
      
      // Initialize Face Landmarker
      faceLandmarker = await FaceLandmarker.createFromOptions(filesetResolver, {
        baseOptions: {
          modelAssetPath: `https://storage.googleapis.com/mediapipe-models/face_landmarker/face_landmarker/float16/1/face_landmarker.task`,
          delegate: "GPU"
        },
        runningMode: "VIDEO",
        numFaces: 1
      });
      
      statusDiv.innerText = "Model loaded. Waiting for camera permissions...";
      startCamera();
    }

    async function startCamera() {
      try {
        const stream = await navigator.mediaDevices.getUserMedia({ video: true });
        video.srcObject = stream;
        video.addEventListener("loadeddata", () => {
          statusDiv.innerText = "Running Detection...";
          predictWebcam();
        });
      } catch (err) {
        statusDiv.innerText = "Error accessing webcam. See console.";
        console.error("Error accessing webcam:", err);
      }
    }

    async function predictWebcam() {
      // 1. Clear previous drawings
      overlayCtx.clearRect(0, 0, overlayCanvas.width, overlayCanvas.height);
      
      // 2. Draw ROI bounding box on original video overlay (Blue)
      overlayCtx.strokeStyle = "blue";
      overlayCtx.lineWidth = 2;
      overlayCtx.strokeRect(roiLeft, roiTop, roiWidth, roiHeight);

      if (video.currentTime !== lastVideoTime) {
        lastVideoTime = video.currentTime;

        // --- ROI Crop Logic ---
        // Draw only the cropped region from the video onto the offscreen canvas
        cropCtx.drawImage(
          video,
          roiLeft, roiTop, roiWidth, roiHeight, // Source crop coordinates
          0, 0, roiWidth, roiHeight             // Destination canvas coordinates
        );

        // Detect faces on the CROPPED canvas instead of the full video
        const results = faceLandmarker.detectForVideo(cropCanvas, performance.now());

        if (results.faceLandmarks && results.faceLandmarks.length > 0) {
          
          // A. Draw landmarks on the crop canvas (Red) to verify crop detection works
          cropCtx.fillStyle = "red";
          for (const landmarks of results.faceLandmarks) {
            for (const pt of landmarks) {
              const px = pt.x * roiWidth;
              const py = pt.y * roiHeight;
              cropCtx.beginPath();
              cropCtx.arc(px, py, 2, 0, 2 * Math.PI);
              cropCtx.fill();
            }
          }

          // B. Remap coordinates to the original video dimensions (Green)
          overlayCtx.fillStyle = "green";
          for (const landmarks of results.faceLandmarks) {
            for (const pt of landmarks) {
              // Convert to pixels in the crop, then add the original crop offset
              const pxOrig = (pt.x * roiWidth) + roiLeft;
              const pyOrig = (pt.y * roiHeight) + roiTop;
              
              overlayCtx.beginPath();
              overlayCtx.arc(pxOrig, pyOrig, 3, 0, 2 * Math.PI);
              overlayCtx.fill();
            }
          }
        }
      }

      // Keep looping
      requestAnimationFrame(predictWebcam);
    }

    initializeMediaPipe();
  </script>
</body>
</html>
```

**Comment by RandomUserUsingGitHub** [comment]
Hello @akashvverma1995,

I really appreciate your response. Since it has almost been two years since I opened this thread originally, I can't quite remember what I eventually came up with. But I believe I implemented something similar to your solution.

Thank you again for your time.
Sincerely,
A random user using github
