### ISSUE TITLE
Face mesh build error

### ISSUE THREAD

**Issue by Hemanth-TS** [google-ai-edge/mediapipe#5714]
### OS Platform and Distribution

Ubuntu 20.04

### Programming Language and version

python 3.9

### Installed using virtualenv? pip? Conda?(if python)

conda 

### MediaPipe version

0.10.14

### Bazel version

7.4

### Android AAR (if android)

None

### OpenCV version (if running on desktop)

4.8.0

### Describe the problem

Build error

### Complete Logs

```shell
I was trying to build face_mesh using cuda for gpu support ,
 
"CUDA_TOOLKIT_PATH="/usr/local/cuda" HERMETIC_CUDNN_VERSION="8.6" bazel build -c opt --config=cuda //mediapipe/examples/desktop/face_mesh:face_mesh_gpu"

I ran into the following error 
Starting local Bazel server and connecting to it...
DEBUG: /home/ipcam/.cache/bazel/_bazel_ipcam/be4e6a33c6a81d7c2f02001ee40b651b/external/org_tensorflow/third_party/py/python_repo.bzl:96:14: 
HERMETIC_PYTHON_VERSION variable was not set correctly, using default version.
Python 3.9 will be used.
To select Python version, either set HERMETIC_PYTHON_VERSION env variable in
your shell:
  export HERMETIC_PYTHON_VERSION=3.12
OR pass it as an argument to bazel command directly or inside your .bazelrc
file:
  --repo_env=HERMETIC_PYTHON_VERSION=3.12
DEBUG: /home/ipcam/.cache/bazel/_bazel_ipcam/be4e6a33c6a81d7c2f02001ee40b651b/external/org_tensorflow/third_party/py/python_repo.bzl:107:10: Using hermetic Python 3.9
DEBUG: /home/ipcam/.cache/bazel/_bazel_ipcam/be4e6a33c6a81d7c2f02001ee40b651b/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: /home/ipcam/.cache/bazel/_bazel_ipcam/be4e6a33c6a81d7c2f02001ee40b651b/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'pybind11_bazel' because it already exists.
DEBUG: /home/ipcam/.cache/bazel/_bazel_ipcam/be4e6a33c6a81d7c2f02001ee40b651b/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'XNNPACK' because it already exists.
DEBUG: /home/ipcam/.cache/bazel/_bazel_ipcam/be4e6a33c6a81d7c2f02001ee40b651b/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: /home/ipcam/.cache/bazel/_bazel_ipcam/be4e6a33c6a81d7c2f02001ee40b651b/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: /home/ipcam/.cache/bazel/_bazel_ipcam/be4e6a33c6a81d7c2f02001ee40b651b/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: /home/ipcam/.cache/bazel/_bazel_ipcam/be4e6a33c6a81d7c2f02001ee40b651b/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'zlib' because it already exists.
DEBUG: /home/ipcam/.cache/bazel/_bazel_ipcam/be4e6a33c6a81d7c2f02001ee40b651b/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'rules_android_ndk' because it already exists.
DEBUG: /home/ipcam/.cache/bazel/_bazel_ipcam/be4e6a33c6a81d7c2f02001ee40b651b/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: /home/ipcam/.cache/bazel/_bazel_ipcam/be4e6a33c6a81d7c2f02001ee40b651b/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'pybind11' because it already exists.
DEBUG: /home/ipcam/.cache/bazel/_bazel_ipcam/be4e6a33c6a81d7c2f02001ee40b651b/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'pybind11_protobuf' because it already exists.
DEBUG: /home/ipcam/.cache/bazel/_bazel_ipcam/be4e6a33c6a81d7c2f02001ee40b651b/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'com_github_glog_glog' because it already exists.
INFO: Repository cuda_cudnn instantiated at:
  /home/ipcam/Downloads/face_recog/Drowsiness-Detection-Mediapipe/mediapipe/WORKSPACE:644:29: in <toplevel>
  /home/ipcam/.cache/bazel/_bazel_ipcam/be4e6a33c6a81d7c2f02001ee40b651b/external/org_tensorflow/third_party/gpus/cuda/hermetic/cuda_redist_init_repositories.bzl:514:15: in cudnn_redist_init_repository
Repository rule cudnn_repo defined at:
  /home/ipcam/.cache/bazel/_bazel_ipcam/be4e6a33c6a81d7c2f02001ee40b651b/external/org_tensorflow/third_party/gpus/cuda/hermetic/cuda_redist_init_repositories.bzl:434:29: in <toplevel>
ERROR: An error occurred during the fetch of repository 'cuda_cudnn':
   Traceback (most recent call last):
	File "/home/ipcam/.cache/bazel/_bazel_ipcam/be4e6a33c6a81d7c2f02001ee40b651b/external/org_tensorflow/third_party/gpus/cuda/hermetic/cuda_redist_init_repositories.bzl", line 432, column 45, in _cudnn_repo_impl
		_use_downloaded_cudnn_redistribution(repository_ctx)
	File "/home/ipcam/.cache/bazel/_bazel_ipcam/be4e6a33c6a81d7c2f02001ee40b651b/external/org_tensorflow/third_party/gpus/cuda/hermetic/cuda_redist_init_repositories.bzl", line 394, column 35, in _use_downloaded_cudnn_redistribution
		version = cuda_version.split(".")[0],
Error: 'NoneType' value has no field or method 'split'
ERROR: /home/ipcam/Downloads/face_recog/Drowsiness-Detection-Mediapipe/mediapipe/WORKSPACE:644:29: fetching cudnn_repo rule //external:cuda_cudnn: Traceback (most recent call last):
	File "/home/ipcam/.cache/bazel/_bazel_ipcam/be4e6a33c6a81d7c2f02001ee40b651b/external/org_tensorflow/third_party/gpus/cuda/hermetic/cuda_redist_init_repositories.bzl", line 432, column 45, in _cudnn_repo_impl
		_use_downloaded_cudnn_redistribution(repository_ctx)
	File "/home/ipcam/.cache/bazel/_bazel_ipcam/be4e6a33c6a81d7c2f02001ee40b651b/external/org_tensorflow/third_party/gpus/cuda/hermetic/cuda_redist_init_repositories.bzl", line 394, column 35, in _use_downloaded_cudnn_redistribution
		version = cuda_version.split(".")[0],
Error: 'NoneType' value has no field or method 'split'
ERROR: /home/ipcam/Downloads/face_recog/Drowsiness-Detection-Mediapipe/mediapipe/mediapipe/examples/desktop/face_mesh/BUILD:38:10: error loading package 'mediapipe/modules/face_landmark': at /home/ipcam/Downloads/face_recog/Drowsiness-Detection-Mediapipe/mediapipe/mediapipe/framework/tool/mediapipe_graph.bzl:26:6: at /home/ipcam/.cache/bazel/_bazel_ipcam/be4e6a33c6a81d7c2f02001ee40b651b/external/org_tensorflow/tensorflow/lite/core/shims/cc_library_with_tflite.bzl:6:6: at /home/ipcam/.cache/bazel/_bazel_ipcam/be4e6a33c6a81d7c2f02001ee40b651b/external/org_tensorflow/tensorflow/tensorflow.bzl:13:5: Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': no such package '@cuda_cudnn//': 'NoneType' value has no field or method 'split' and referenced by '//mediapipe/examples/desktop/face_mesh:face_mesh_gpu'
ERROR: Analysis of target '//mediapipe/examples/desktop/face_mesh:face_mesh_gpu' failed; build aborted: Analysis failed
INFO: Elapsed time: 4.837s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (50 packages loaded, 249 targets configured)
    currently loading: mediapipe/modules/face_landmark ... (2 packages)
    Fetching repository @local_config_cc; starting
    Fetching repository @local_config_cuda; Restarting.
"
```

**Comment by Hemanth-TS** [comment]
I’ve modified the configuration and am now using:

Python 3.8
Bazel 6.1.1
MediaPipe 0.10.13
I successfully ran the Hello World example, I'm  actually working with a Python script that utilizes the Face Mesh model. I want to make sure it's utilizing the GPU properly. Could you guide me on how to set this up?

**Comment by kuaashish** [comment]
Hi @schmidt-sebastian,

Do you have any suggestions on the above query?

Thank you!!

**Comment by Hemanth-TS** [comment]
Ultimately what i need to do now is 
-Enable CUDA support for face-mesh.
-Run multiple Python scripts utilizing CUDA-enabled face-mesh.

Previously, I referred to https://ai.google.dev/edge/mediapipe/framework/getting_started/gpu_support, the sections on TensorFlow and CUDA support.

**Comment by Hemanth-TS** [comment]
@kuaashish @schmidt-sebastian  could either of you follow up on this?

**Comment by Hemanth-TS** [comment]
@kuaashish Any updates on this?

**Comment by kalyan2789g** [comment]
Hi @Hemanth-TS,

Thank you for reporting this issue. This issue is related to the legacy feature that is no longer actively supported and support has been completely ended.

We recommend migrating to the new MediaPipe API’s for continued support and access to the most recent documentation to new MediaPipe API’s [here](https://ai.google.dev/edge/mediapipe/solutions/guide). Please consult the [release notes](https://github.com/google-ai-edge/mediapipe/releases) for information on the latest updates.

If you encounter any issues with the new MediaPipe API’s, please open a new GitHub issue with detailed debugging information to facilitate our investigation.

Please follow the [release notes](https://github.com/google-ai-edge/mediapipe/releases) to stay up to date with the latest developments which are happening in the MediaPipe space.
MediaPipe
