### ISSUE TITLE
RuntimeError: ; Unable to find the type for stream "image".

### ISSUE THREAD

**Issue by Kalit31** [google-ai-edge/mediapipe#5736]
### OS Platform and Distribution

Linux Ubuntu 18.04.6 LTS (Bionic Beaver)

### Compiler version

-

### Programming Language and version

Python 3.8.12

### Installed using virtualenv? pip? Conda?(if python)

-

### MediaPipe version

0.10.7

### Bazel version

-

### XCode and Tulsi versions (if iOS)

-

### Android SDK and NDK versions (if android)

-

### Android AAR (if android)

None

### OpenCV version (if running on desktop)

4.10.0.84

### Describe the problem

I am trying to build some applications using mediapipe on a Nvidia Jetson machine (4 CPU cores ARMv8 Processor, NVIDIA Tegra X1). I had installed a mediapipe version through pip, but it was not using the GPUs available on the machine.  ``` INFO: Created TensorFlow Lite XNNPACK delegate for CPU. ``` To make use of the available GPUs, I followed the documentation available here:  1. https://jetson-docs.com/libraries/mediapipe/overview 2. https://jetson-docs.com/libraries/mediapipe/l4t32.7.1/py3.8.0  However, when I am trying to run the sample program, it throws the following error:

### Complete Logs

```shell
Traceback (most recent call last):
  File "ar-filters/app.py", line 12, in <module>
    face_mesh_videos = mp_face_mesh.FaceMesh(static_image_mode=False, max_num_faces=1, min_detection_confidence=0.5, min_tracking_confidence=0.3)
  File "/home/epl/.local/lib/python3.8/site-packages/mediapipe/python/solutions/face_mesh.py", line 95, in __init__
    super().__init__(
  File "/home/epl/.local/lib/python3.8/site-packages/mediapipe/python/solution_base.py", line 276, in __init__
    canonical_graph_config_proto = self._initialize_graph_interface(
  File "/home/epl/.local/lib/python3.8/site-packages/mediapipe/python/solution_base.py", line 428, in _initialize_graph_interface
    self._input_stream_type_info = {
  File "/home/epl/.local/lib/python3.8/site-packages/mediapipe/python/solution_base.py", line 429, in <dictcomp>
    get_name(tag_index_name): get_stream_packet_type(tag_index_name)
  File "/home/epl/.local/lib/python3.8/site-packages/mediapipe/python/solution_base.py", line 426, in get_stream_packet_type
    validated_graph.registered_stream_type_name(stream_name))
RuntimeError: ; Unable to find the type for stream "image".  It may be set to AnyType or something else that isn't determinable, or the type may be defined but not registered.
```

**Comment by kuaashish** [comment]
Hi @Kalit31,

Based on the information you have shared, there appear to be two issues:

- **Unsupported Python Version:** It seems you are using an unsupported Python version. The supported versions, as [mentioned](https://ai.google.dev/edge/mediapipe/solutions/setup_python#supported_platforms_and_versions) in the documentation, are 3.9 to 3.12.
- **Legacy Face Mesh:** It looks like you might still be using the legacy face mesh, which has been upgraded to the Face Landmarker Task API. Please note that support for the legacy solution has ended(see [here](https://ai.google.dev/edge/mediapipe/solutions/guide#legacy)), and you can find more details in the [documentation](https://ai.google.dev/edge/mediapipe/solutions/guide#available_solutions).

Please let me know if you need further clarification or assistance!

Thank you!!

**Comment by Kalit31** [comment]
Hi @kuaashish,
Thanks for the quick response!
Yes, I was using the legacy face mesh. The below docs seem to be outdated then?
1. https://jetson-docs.com/libraries/mediapipe/overview
2. https://jetson-docs.com/libraries/mediapipe/l4t32.7.1/py3.8.0

Let me try with 'Face Landmarker Task API'. Will update you.

**Comment by Kalit31** [comment]
Thanks for the detailed response!
Is there any way I can use legacy versions of the face mesh and make use of the GPU support available in the Jetson machine? 

The legacy face mesh was working perfectly fine, just that it was not making use of the available GPUs. Considering the limited (or unavailable) support for the new Task API on Jetson, can you suggest some approach to make use of the legacy version?

**Comment by kuaashish** [comment]
Hi @Kalit31,

There is a community-based implementation available at [this GitHub repository](https://github.com/anion0278/mediapipe-jetson), which supports GPUs and is based on legacy solutions. While it may work with the GPU, for support with the new Task API on Jetson, we recommend submitting a feature request [here](https://github.com/google-ai-edge/mediapipe/issues/new?assignees=&labels=type%3Afeature&projects=&template=14-feature-request-issue-template.yaml), and request you to close this issue, Future implementations may be considered based on community demand and our discussion.

Thank you!!
