### ISSUE TITLE
Error building on windows 11 (maybe docs is out of date?)

### ISSUE THREAD

**Issue by stormsc1** [google-ai-edge/mediapipe#5748]
**Environment**
 - Python 3.9 (tried with 3.6, 3.11, and 3.12)
 - Bazel though Bazelisk
 - BAZEL_VS=C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
 - BAZEL_VC=C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC
 - BAZEL_VC_FULL_VERSION=14.29.30133
 - BAZEL_WINSDK_FULL_VERSION=10.0.19041.0

```python
C:\Users\wow\mediapipe>bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="C:/Users/wow/AppData/Local/Programs/Python/Python39/python.exe" mediapipe/examples/desktop/hello_world
INFO: Repository python_version_repo instantiated at:
  C:/users/wow/mediapipe/WORKSPACE:324:25: in <toplevel>
  C:/users/wow/_bazel_cawthorne/x4bdikh4/external/org_tensorflow/third_party/xla/third_party/py/python_init_repositories.bzl:13:22: in python_init_repositories
Repository rule python_repository defined at:
  C:/users/wow/_bazel_cawthorne/x4bdikh4/external/org_tensorflow/third_party/py/python_repo.bzl:151:36: in <toplevel>
ERROR: An error occurred during the fetch of repository 'python_version_repo':
   Traceback (most recent call last):
        File "C:/users/wow/_bazel_cawthorne/x4bdikh4/external/org_tensorflow/third_party/py/python_repo.bzl", line 12, column 34, in _python_repository_impl
                version = _get_python_version(ctx)
        File "C:/users/wow/_bazel_cawthorne/x4bdikh4/external/org_tensorflow/third_party/py/python_repo.bzl", line 87, column 21, in _get_python_version
                fail("""
Error in fail:
Cannot match hermetic Python version to system Python version.
System Python was not found.
ERROR: C:/users/wow/mediapipe/WORKSPACE:324:25: fetching python_repository rule //external:python_version_repo: Traceback (most recent call last):
        File "C:/users/wow/_bazel_cawthorne/x4bdikh4/external/org_tensorflow/third_party/py/python_repo.bzl", line 12, column 34, in _python_repository_impl
                version = _get_python_version(ctx)
        File "C:/users/wow/_bazel_cawthorne/x4bdikh4/external/org_tensorflow/third_party/py/python_repo.bzl", line 87, column 21, in _get_python_version
                fail("""
Error in fail:
Cannot match hermetic Python version to system Python version.
System Python was not found.
ERROR: Error computing the main repository mapping: no such package '@python_version_repo//':
Cannot match hermetic Python version to system Python version.
System Python was not found.
Loading:
```

I am aware windows builds are not the norm. I would just build on Linux, if it wasnt because i needed the windows binaries for Unreal Engine project.

**Comment by willyweichen** [comment]
Same problem:

Python 3.10.14
BAZEL_VS=C:\Program Files\Microsoft Visual Studio\2022\Community
BAZEL_VC=C:\Program Files\Microsoft Visual Studio\2022\Community\VC
BAZEL_VC_FULL_VERSION=14.42.34433
BAZEL_WINSDK_FULL_VERSION=10.0.22621.3233

C:\Mediapipe\mediapipe-master>bazel build -c opt --define MWDIAPIPE_DISABLE_GPU=0 PYTHON_BIN_PATH="C:\Users\YAO\anaconda3\envs\hamer\python.exe" mediapipe/examples/desktop/hello_world
Starting local Bazel server and connecting to it...
INFO: Repository python_version_repo instantiated at:
  C:/mediapipe/mediapipe-master/WORKSPACE:324:25: in <toplevel>
  C:/users/yao/_bazel_yao/oieertoi/external/org_tensorflow/third_party/xla/third_party/py/python_init_repositories.bzl:13:22: in python_init_repositories
Repository rule python_repository defined at:
  C:/users/yao/_bazel_yao/oieertoi/external/org_tensorflow/third_party/py/python_repo.bzl:151:36: in <toplevel>
ERROR: C:/users/yao/_bazel_yao/oieertoi/external/org_tensorflow/third_party/py/python_repo.bzl:87:21: An error occurred during the fetch of repository 'python_version_repo':
   Traceback (most recent call last):
        File "C:/users/yao/_bazel_yao/oieertoi/external/org_tensorflow/third_party/py/python_repo.bzl", line 12, column 34, in _python_repository_impl
                version = _get_python_version(ctx)
        File "C:/users/yao/_bazel_yao/oieertoi/external/org_tensorflow/third_party/py/python_repo.bzl", line 87, column 21, in _get_python_version
                fail("""
Error in fail:
Cannot match hermetic Python version to system Python version.
System Python was not found.
ERROR: Error computing the main repository mapping: no such package '@@python_version_repo//':
Cannot match hermetic Python version to system Python version.
System Python was not found.
Computing main repo mapping:

**Comment by stormsc1** [comment]
I tried building a bunch of versions from [releases](https://github.com/google-ai-edge/mediapipe/releases).

The issue does not appear to be present in v0.10.2, v0.10.10, v0.10.14 v0.10.15 (second latest release).

@willyweichen If you don't care for the updates in v0.10.18, then v0.10.15 seems to be an option.

**Comment by definability** [comment]
It seems like one dependency (I believe it is TensorFlow) looks for `python3`. To my surprise, the official Python 3.11.9 installer does not contain `python3.exe` file &mdash; only `python.exe` in my `%LOCALAPPDATA%\Programs\Python\Python311`. That is why the command `python3` leads to `%LOCALAPPDATA%\Microsoft\WindowsApps\python3.exe` by default. If you did not install Python using Microsoft Store, this executable opens the Microsoft Store page of Python 3.

I used a dirty workaround: create a copy of `python.exe` named `python3.exe` (and more methods on StackOverflow: https://stackoverflow.com/q/39910730).

**Comment by cima** [comment]
Yes Tensorflow has a build script in bazel (namely [python_repo.bzl](https://github.com/tensorflow/tensorflow/blob/a6ffca4a0f5995017214832334a71894e69ebf00/third_party/xla/third_party/py/python_repo.bzl#L143)) that is getting version of python by calling `python3 --version` which results in failure on windows.

Although the copy hack does the job I think making a symbolic link is a cleaner solution.
```
mklink "C:\path\to\Python3\python3.exe" "C:\path\to\Python3\python.exe"
```
If you don't know the python path in a first place it is easy to see detectable python using command `where python`

**Comment by akashvverma1995** [comment]
Hi @stormsc1 



Please add the following line to your .bazelrc file:
`common --repo_env=HERMETIC_PYTHON_VERSION=3.9`

After adding it, try building the project again. I hope this resolves your issue.
