### ISSUE TITLE
Is it true that python 3.10.2 is no longer supported in version 10.18?

### ISSUE THREAD

**Issue by jhlibra** [google-ai-edge/mediapipe#5753]
### OS Platform and Distribution

win10

### Compiler version

14.29.30133

### Programming Language and version

c++

### Installed using virtualenv? pip? Conda?(if python)

python3.10.2

### MediaPipe version

10.18

### Bazel version

6.10

### Android AAR (if android)

None

### OpenCV version (if running on desktop)

4.6

### Describe the problem

Is it true that python 3.10.2 is no longer supported in version 10.18?

### Complete Logs

```shell
PS C:\Users\RZTest> cd D:\Mediapipe\mediapipe\mediapipe
PS D:\Mediapipe\mediapipe\mediapipe> bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1  --action_env PYTHON_BIN_PATH="C:\\Python310\\python.exe" mediapipe/examples/desktop/hello_world:hello_world --verbose_failures
INFO: Repository python_version_repo instantiated at:
  D:/mediapipe/mediapipe/mediapipe/WORKSPACE:299:25: in <toplevel>
  C:/users/rztest/_bazel_rztest/fkji4khh/external/org_tensorflow/third_party/xla/third_party/py/python_init_repositories.bzl:13:22: in python_init_repositories
Repository rule python_repository defined at:
  C:/users/rztest/_bazel_rztest/fkji4khh/external/org_tensorflow/third_party/py/python_repo.bzl:151:36: in <toplevel>
ERROR: An error occurred during the fetch of repository 'python_version_repo':
   Traceback (most recent call last):
        File "C:/users/rztest/_bazel_rztest/fkji4khh/external/org_tensorflow/third_party/py/python_repo.bzl", line 12, column 34, in _python_repository_impl
                version = _get_python_version(ctx)
        File "C:/users/rztest/_bazel_rztest/fkji4khh/external/org_tensorflow/third_party/py/python_repo.bzl", line 87, column 21, in _get_python_version
                fail("""
Error in fail:
Cannot match hermetic Python version to system Python version.
System Python was not found.
ERROR: Error computing the main repository mapping: no such package '@@python_version_repo//':
Cannot match hermetic Python version to system Python version.
System Python was not found.

Is it true that python 3.10.2 is no longer supported in version 10.18?
Is there an official and detailed tutorial on how to install and use Mediapipe on windows?
```

**Comment by kuaashish** [comment]
Hi @jhlibra,

Closing this issue as a duplicate of [Issue #5754](https://github.com/google-ai-edge/mediapipe/issues/5754). Please refer to that issue for further updates.

Thank you!!
