### ISSUE TITLE
Is it true that python 3.10.2 is no longer supported in version 10.18?

### ISSUE THREAD

**Issue by jhlibra** [google-ai-edge/mediapipe#5754]
### OS Platform and Distribution

win10

### Compiler version

14.29.30133

### Programming Language and version

c++

### Installed using virtualenv? pip? Conda?(if python)

python3.10.2

### MediaPipe version

10.18

### Bazel version

6.10

### Android AAR (if android)

None

### OpenCV version (if running on desktop)

4.6

### Describe the problem

Is it true that python 3.10.2 is no longer supported in version 10.18?Is it true that python 3.10.2 is no longer supported in version 10.18? Is there an official and detailed tutorial on how to install and use Mediapipe on windows?

### Complete Logs

```shell
PS C:\Users\RZTest> cd D:\Mediapipe\mediapipe\mediapipe
PS D:\Mediapipe\mediapipe\mediapipe> bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1  --action_env PYTHON_BIN_PATH="C:\\Python310\\python.exe" mediapipe/examples/desktop/hello_world:hello_world --verbose_failures
INFO: Repository python_version_repo instantiated at:
  D:/mediapipe/mediapipe/mediapipe/WORKSPACE:299:25: in <toplevel>
  C:/users/rztest/_bazel_rztest/fkji4khh/external/org_tensorflow/third_party/xla/third_party/py/python_init_repositories.bzl:13:22: in python_init_repositories
Repository rule python_repository defined at:
  C:/users/rztest/_bazel_rztest/fkji4khh/external/org_tensorflow/third_party/py/python_repo.bzl:151:36: in <toplevel>
ERROR: An error occurred during the fetch of repository 'python_version_repo':
   Traceback (most recent call last):
        File "C:/users/rztest/_bazel_rztest/fkji4khh/external/org_tensorflow/third_party/py/python_repo.bzl", line 12, column 34, in _python_repository_impl
                version = _get_python_version(ctx)
        File "C:/users/rztest/_bazel_rztest/fkji4khh/external/org_tensorflow/third_party/py/python_repo.bzl", line 87, column 21, in _get_python_version
                fail("""
Error in fail:
Cannot match hermetic Python version to system Python version.
System Python was not found.
ERROR: Error computing the main repository mapping: no such package '@@python_version_repo//':
Cannot match hermetic Python version to system Python version.
System Python was not found.
```

**Comment by kuaashish** [comment]
Hi @jhlibra,

It appears to be a Python version related issue, possibly with version 0.10.18. A similar issue has already been reported here: https://github.com/google-ai-edge/mediapipe/issues/5748. Please allow us some time to reproduce the issue and explore potential workarounds.

Thank you!!

**Comment by MrKQA** [comment]
Modify the default_python_version in WORKSPACE to the version number of PYTHON_BIN_PATH
python_init_repositories(
    default_python_version = "3.11",
    local_wheel_dist_folder = "dist",
    local_wheel_inclusion_list = ["mediapipe*"],
    local_wheel_workspaces = ["//:WORKSPACE"],
    requirements = {
        "3.9": "//:requirements_lock.txt",
        "3.10": "//:requirements_lock_3_10.txt",
        "3.11": "//:requirements_lock_3_11.txt",
        "3.12": "//:requirements_lock_3_12.txt",
    },
)

**Comment by schmidt-sebastian** [comment]
Hello - we have now (finally) published a new MediaPipe SDK to PyPi (version 0.10.30) that works for all Python version greater than 3.9. This SDK has been completely rewritten to decouple us from the underlying dependencies, and if you encounter any issues, please open a new issue on GItHub.

Note that this release drops support for our legacy solutions API and temporarilty removes the Holistic Landmarker Task API, which we plan on adding back soon.

Thanks!
