### ISSUE TITLE
Reducing Latency for Hand-Tracking Solution in Python

### ISSUE THREAD

**Issue by MarcKr3** [google-ai-edge/mediapipe#5789]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

Yes

### OS Platform and Distribution

Windows 10 amd64x

### MediaPipe Tasks SDK version

Mediapipe Version: 0.10.20

### Task name (e.g. Image classification, Gesture recognition etc.)

Hand landmark detection

### Programming Language and version (e.g. C++, Python, Java)

Python

### Describe the actual behavior

Using the LITE Model (model_complexity=0), I'm measuring Latency of 35-27ms 

### Describe the expected behaviour

According to "https://ai.google.dev/edge/mediapipe/solutions/vision/hand_landmarker", the FULL Model (model_complexity=1)  has a latency of CPU:17ms, GPU:12ms

### Standalone code/steps you may have used to try to get what you need

The way I measure latency is as follows:

**Comment by kuaashish** [comment]
Hi @MarcKr3,

Thank you for reaching out. Below are some answers regarding the support you are looking for:

> - Hardware Acceleration:

  Based on the code snippet and version you are using, it appears you are utilizing the legacy hand tracking solution. Please 
  note that this solution has been upgraded and is now integrated into the Hand Landmarker Task API, as outlined in the 
  [documentation](https://developers.google.com/mediapipe/solutions/guide#legacy). We have discontinued support for 
  legacy solutions and are no longer maintaining them.

  The upgraded Task API offers improved performance and is easier to implement for your use case. It also supports GPU 
  acceleration. For GPU configuration details, please refer to this https://github.com/google-ai-edge/mediapipe/issues/5426. We recommend transitioning to the new Hand 
 Task API, which you can explore through the guidelines [here](https://developers.google.com/mediapipe/solutions/vision/hand_landmarker). A Python guide is available [here](https://developers.google.com/mediapipe/solutions/vision/hand_landmarker/python), along with a [Python notebook example](https://colab.sandbox.google.com/github/googlesamples/mediapipe/blob/main/examples/hand_landmarker/python/hand_landmarker.ipynb). If you encounter similar behavior in the new Task API, please let us know.

> - Tracking Specific Landmarks:

  Currently, it is not possible to track only specific landmarks with the Hand Landmarker. However, MediaPipe's model maker 
  can assist with this feature, though it is not yet available for the Hand Landmarker.

> - Switching to C++:

  If you wish to switch to C++, we recommend opening a new issue using this [template ](https://github.com/google-ai-edge/mediapipe/issues/new?assignees=&labels=type%3Abuild%2Finstall&projects=&template=15-build-install-issue-template.yaml)and providing the necessary details and complete error logs. Our team will be happy to assist you in resolving this.

Please let us know if you need further assistance.

**Comment by MarcKr3** [comment]
Thank You for Your answer!

Sorry, I thought I'm running the latest version because I was working with the most recent pip install.
(pip show mediapipe -> mediapipe Version: 0.10.20)

The python notebook for landmark detection in images worked, but i was unable to implement the "live stream"-task.
I tried my hardest following the guides You shared, but failed horribly...

```
import mediapipe as mp
from mediapipe import solutions
from mediapipe.framework.formats import landmark_pb2
from mediapipe.tasks import python
from mediapipe.tasks.python import vision
import cv2
import numpy as np

BaseOptions = python.BaseOptions
HandLandmarker = vision.HandLandmarker
HandLandmarkerOptions = vision.HandLandmarkerOptions
HandLandmarkerResult = vision.HandLandmarkerResult
VisionRunningMode = vision.RunningMode

# Create a hand landmarker instance with the live stream mode:
def print_result(result: HandLandmarkerResult, output_image: mp.Image, timestamp_ms: int):  # type: ignore
    print('hand landmarker result: {}'.format(result))

options = HandLandmarkerOptions(base_options=BaseOptions(model_asset_path='D:\Desktop\MIDIHands\hand_landmarker.task'), running_mode=VisionRunningMode.LIVE_STREAM, result_callback=print_result)

cap = cv2.VideoCapture(0)

MARGIN = 10  # pixels
FONT_SIZE = 1
FONT_THICKNESS = 1
HANDEDNESS_TEXT_COLOR = (88, 205, 54) # vibrant green

def draw_landmarks_on_image(rgb_image, results):
  hand_landmarks_list = results.hand_landmarks
  handedness_list = results.handedness
  annotated_image = np.copy(rgb_image)

  # Loop through the detected hands to visualize.
  for idx in range(len(hand_landmarks_list)):
    hand_landmarks = hand_landmarks_list[idx]
    handedness = handedness_list[idx]

    # Draw the hand landmarks.
    hand_landmarks_proto = landmark_pb2.NormalizedLandmarkList()
    hand_landmarks_proto.landmark.extend([landmark_pb2.NormalizedLandmark(x=landmark.x, y=landmark.y, z=landmark.z) for landmark in hand_landmarks])
    
    solutions.drawing_utils.draw_landmarks(annotated_image, hand_landmarks_proto, solutions.hands.HAND_CONNECTIONS, solutions.drawing_styles.get_default_hand_landmarks_style(), solutions.drawing_styles.get_default_hand_connections_style())

    # Get the top left corner of the detected hand's bounding box.
    height, width, _ = annotated_image.shape
    x_coordinates = [landmark.x for landmark in hand_landmarks]
    y_coordinates = [landmark.y for landmark in hand_landmarks]
    text_x = int(min(x_coordinates) * width)
    text_y = int(min(y_coordinates) * height) - MARGIN

    # Draw handedness (left or right hand) on the image.
    cv2.putText(annotated_image, f"{handedness[0].category_name}", (text_x, text_y), cv2.FONT_HERSHEY_DUPLEX, FONT_SIZE, HANDEDNESS_TEXT_COLOR, FONT_THICKNESS, cv2.LINE_AA)

  return annotated_image

with HandLandmarker.create_from_options(options) as landmarker:
    while cap.isOpened():
        ret, frame = cap.read()
        frame_timestamp_ms = cap.get(cv2.CAP_PROP_POS_MSEC)

        image = cv2.flip(frame, 1)

        image = mp.Image(image_format=mp.ImageFormat.SRGB, data=image)
        
        results = landmarker.detect_async(image,int(frame_timestamp_ms))
        
        annotated_image = draw_landmarks_on_image(image, results)

        key = cv2.waitKey(10) & 0xFF

        cv2.imshow("MIDIHands", annotated_image)

        if key == ord('q'):
            break

cap.release()
cv2.destroyAllWindows()
```

This yields the error:
```
hand landmarker result: HandLandmarkerResult(handedness=[], hand_landmarks=[], hand_world_landmarks=[])
Traceback (most recent call last):
  File "d:\Desktop\MIDIHands\newAPI.py", line 67, in <module>
    annotated_image = draw_landmarks_on_image(image, results)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Desktop\MIDIHands\newAPI.py", line 29, in draw_landmarks_on_image
    hand_landmarks_list = results.hand_landmarks
                          ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'hand_landmarks'
```
Could You point towards an implementation of live stream-hand landmark detection?


Regarding the Hardware Acceleration:
I'm running Windows, which it isn't supported on yet, right?

Thanks for the Information about the Model Maker and C++.
I'll consider it if updating to the task APIs doesn't work.

**Comment by akashvverma1995** [comment]
Hi @MarcKr3 

I have attached the Hand Landmarker live stream implementation for your reference. Could you please test it on your end and confirm whether it is working as expected?

For this implementation, I am using MediaPipe version 0.10.35. Also, GPU processing is disabled in the build flags. You can refer to the MediaPipe [release notes](https://github.com/google-ai-edge/mediapipe/releases/tag/v0.10.33) for more details regarding this behavior.

Code -
```
import cv2
import time
import mediapipe as mp
from mediapipe.tasks import python
from mediapipe.tasks.python import vision

latest = {"result": None}

def on_result(result, image, timestamp_ms):
    latest["result"] = result

options = vision.HandLandmarkerOptions(
    base_options=python.BaseOptions(model_asset_path="../../Data/models/hand_landmarker.task"),
    running_mode=vision.RunningMode.LIVE_STREAM,
    num_hands=2,
    result_callback=on_result,
)

cap = cv2.VideoCapture(0)
t0 = time.time()

with vision.HandLandmarker.create_from_options(options) as landmarker:
    while cap.isOpened():
        ok, frame = cap.read()
        if not ok:
            break

        rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        mp_image = mp.Image(image_format=mp.ImageFormat.SRGB, data=rgb)
        ts_ms = int((time.time() - t0) * 1000)

        landmarker.detect_async(mp_image, ts_ms)   

  
        result = latest["result"]
        if result and result.hand_landmarks:
            for hand in result.hand_landmarks:
                for lm in hand:
                    x, y = int(lm.x * frame.shape[1]), int(lm.y * frame.shape[0])
                    cv2.circle(frame, (x, y), 4, (0, 255, 0), -1)

        cv2.imshow("hands", frame)
        if cv2.waitKey(1) & 0xFF == ord("q"):
            break

cap.release()
cv2.destroyAllWindows()
```
